---
title: Trabajos
slug: trabajos
output:
  blogdown::html_page:
      toc: TRUE
---

El curso tendrá tres instancias de evaluación:

- **Informe 1** (individual): Correlación y regresión simple (20%). **Entrega: Jueves 29 de Abril**
- **Informe 2** (grupal): Regresión multiple e inferencia estadística (30%). **Entrega: Jueves 3 de Junio**
- **Informe 3** (grupal): Regresión logística, predictores categóricos y supuestos (50%). **Entrega: Viernes 2 de Julio**

La nota ponderada de los trabajos equivaldrá al 60% de la nota del curso y el examen final al 40% restante.

# Pauta de trabajo individual (Informe 1)

Este trabajo abarca la primera parte del curso hasta regresión simple (Sesión 4: Regresión simple 2). Es un informe breve, consistente en preparación y análisis de datos incluyendo como producto final la estimación e interpretación de una regresión simple. Para ello, los pasos son los siguientes:

- seleccionar una base de datos de interés (ver abajo las sugeridas para los trabajos grupales)
- seleccionar las variables a analizar, dar una breve justificación
- generar el código de preparación de datos y la base procesada
- generar el código de análisis y reportar los resultados.

El informe tiene las siguientes secciones:

1. Identificación: Tema y nombre de estudiante
2. Resumen (200 palabras) (0.5p)
3. Antecedentes de la relación estudiada (300 palabras) (0.5p)
4. Metodología (1p)

    4.1- Datos (descripción)

    4.2- Variables (descripción y tabla con estadísticos descriptivos)
5. Análisis (2p)

    5.1 Análisis descriptivo

    5.2 Modelo de regresión

6. Bibliografía

7. Anexos: código de preparación de datos y código de análisis (2p)

Fecha de entrega: ver Planificación.

**Ejemplo para Informe 1 [aquí](../assignment/ejemplocasencovid/ejemploinforme1.html)**

# Pauta de trabajo grupal (Informes 2 y 3)

## Objetivo general

Aplicar los contenidos del curso a una temática de interés en formato de artículo de investigación breve.

## Sobre los temas

De modo de lograr una mayor colaboración desde el equipo docente a sus trabajos, sugerimos desarrollar los siguientes temas:

- Desigualdad social, educación cívica, justicia distributiva, opinión pública
- Estratificación social, política educativa, sociología política
- Economía laboral, relaciones laborales, acción colectiva y condiciones de empleo

Recomendamos utilizar alguna de las siguientes fuentes de datos para realizar los trabajos (para abrir bases de datos en formatos distintos a R revisar nota correspondiente en práctica 1, link [aquí](/assignment/01-code/#2-cargar-base-de-datos)):

- [ELSOC](https://coes.cl/encuesta-panel/) (Ola 1)
  - [Manual de Usuario](/docs/Manual_Usuario_ELSOC_W01_v2.00.pdf)
  - [base de datos Ola 1](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/0KIRBJ&version=2.0)
- [CASEN](http://observatorio.ministeriodesarrollosocial.gob.cl/encuesta-casen-2017) (evt. subset)
- [SIMCE](https://informacionestadistica.agenciaeducacion.cl/#/bases) (evt. subset)
- [LAPOP](https://www.vanderbilt.edu/lapop-espanol/)
- [Desiguales](https://www.desiguales.org/descripcin-del-libro)
- [CEP 83 -  Módulo Desigualdad Social ISSP 2019](https://www.cepchile.cl/cep/encuestas-cep/encuestas-2009-2018/estudio-nacional-de-opinion-publica-mayo-2019)
- [CEP: varios temas/preguntas para encuestas desde 1990 en adelante, muy buen buscador!](https://www.cepchile.cl/cep/site/edic/base/port/buscador.html)
- ISSP (International Social Survey Programme)
  - [Desigualdad Social](https://www.gesis.org/issp/modules/issp-modules-by-topic/social-inequality)
  - [Rol del Gobierno](https://www.gesis.org/en/issp/modules/issp-modules-by-topic/role-of-government)
  - [Orientaciones del trabajo](https://www.gesis.org/issp/modules/issp-modules-by-topic/work-orientations/2015)
- [ICTWSS](http://uva-aias.net/en/ictwss)
- Encuestas Laborales
  - [ENE](http://bancodatosene.ine.cl/)
  - [ESI](https://www.ine.cl/estadisticas/sociales/ingresos-y-gastos/encuesta-suplementaria-de-ingresos)
  - [ENUT](https://www.ine.cl/estadisticas/sociales/genero/uso-del-tiempo)
  - OHL, ENCLA y otras pueden ser solicitadas directamente a **Valentina Andrade**

## Modalidad de trabajo y asesorías

- Trabajo de carácter grupal
  - N° integrantes: **5 estudiantes**. Solo excepcional y justificadamente podrán ser de 4.

- **Inscripción de temas**
  - Debe realizarse a principios de Mayo vía **U-Cursos**
  - El documento debe indicar claramente integrantes, correo, tema y base de datos a utilizar

## Entregas

Este trabajo posee dos entregas, tal como se señala en el programa del curso

- **Informe 2 (avance)**: Su formato es de un borrador de la entrega final. La idea es avanzar en todas las secciones, incluyendo la temática general a abordar así como también datos y variables en la sección de métodos, y análisis descriptivos. El énfasis en esta primera entrega se encuentra en el planteamiento de las hipótesis y el modelo de regresión asociado. Incluye estimar el modelo de regresión múltiple y su  interpretación (total máximo 2000 palabras)

  - Consideraciones: En el caso de los trabajos donde la variable dependiente sea dicotómica, para esta primera entrega la estimación puede ser realizada preliminarmente con regresión lineal, y para la segunda se espera estimación con regresión logística

- **Informe 3 (final)**: Su formato es de artículo/ reporte breve de investigación. En esta entrega se corrigen aspectos del **Informe 2**, junto con profundizar en el chequeo de supuestos, casos influyentes, interacciones. Aquellos grupos que trabajen con una variable dependiente continua deberán realizar además al menos una estimación de regresión logística (y su correspondiente interpretación) con la variable dependiente dicotomizada (total máximo 3.500 palabras).

**Actualización Informe 3**

- Lo central en este informe es incorporar las correcciones al informe 2

- La estimación de regresión logística es opcional (excepto para quienes tengan una variable dependiente dicotómica o que haya sido sugerido dicotomizarla por temas de distribución)

- No se incluye en la evaluación de este informe el chequeo de supuestos del modelo de regresión. De todas maneras en la página quedará un tutorial disponible sobre este tema.

## Secciones del trabajo

1. Título: Breve, lo principal es hacer alusión al objeto central de estudio (variable dependiente) (0,5 pto)

2. Resumen/Abstract (250 palabras), incluye: problema/pregunta, objetivo, datos (y N), resultado principal. (0,5 pto)

3. Introducción: definición de la problemática a abordar, su relevancia y principales conceptos (500 palabras). (2 puntos, 1 por la definición del problema y pregunta, y 1 por la definición conceptual)

- En este apartado es importante considerar:

  - Relevancia del tema de investigación
  - Relevancia del problema de investigación: además de que el "tema" pueda ser relevante (ej: aumento de desigualdad económica, disminución de niveles de participación), la relevancia del problema se refiere a cuál es el aporte distintivo de este estudio desde una perspectiva académica y disciplinar (sociología).
  - Precisar el concepto central que se va a investigar: Ejemplo "vamos a estudiar participación informal, entendiendo por ello la frecuencia de participación en actividades como marchas, boycotts y en redes sociales".
  - Precisar argumento / hipótesis central "proponemos que a medida que aumenta el nivel de contactos con identificación política de izquierda, aumenta la participación política informal"
  - El resto de la introducción usualmente se divide en dos secciones, que también son referidas como marco teórico, marco referencial, revisión bibliográfica, etc. **Título sugerido: antecedentes conceptuales y empíricos**
    - El primer apartado corresponde al objeto central de estudio /variable dependiente (explanandum), donde se profundiza en su origen y definición, y se revisan las principales investigaciones que se asocian a este concepto. (**+/-** 5 referencias)
    - El segundo apartado corresponde a los conceptos relacionados con las variables independientes (explanans) y en los cuales se basan las hipótesis. Se revisan en orden de relevancia. (**+/-** 5 referencias)

4. Objetivos / hipótesis (alrededor de 3) (250 palabras) (1 punto)

5. Metodología: datos (no olvidar número de casos), variables y métodos  (500 palabras). (3 puntos, uno por cada subsección)
- Esta sección también incluye una tabla de descriptivos básicos, y una descripción detallada de la operacionalización y medición de las variables.
- **Sobre la selección de la variable dependiente**: por definición la variable dependiente en regresión múltiple OLS es continua. Escalas tipo likert pueden ser utilizadas en casos justificados y también teniendo en cuenta su variabilidad (si muchos casos se acumulan en pocas categorías la varianza va a ser pequeña, menos posibilidades de covarianza, y por tanto baja probabilidad de encontrar efectos significativos).

6. Análisis (1500 palabras) (6 puntos)
- **La sección de análisis sigue la lógica del trabajo anterior**: análisis descriptivo y luego análisis de modelos de regresión
- Comenzar con análisis descriptivo uni y bivariado, nubes de puntos, tabla de correlaciones (1 punto).
- Introducción del sentido de los modelos en relación a las hipótesis (1 punto)
- Presentación de la(s) tabla(s) (2 puntos)
- Interpretación (4 puntos).
- **sobre número de predictores**: al menos tres

7. Discusión de los resultados, con énfasis en la relación entre variable dependiente e independientes, limitaciones, posibles estudios futuros. (500 palabras) (2 puntos)

8. Video-cápsula de presentación del trabajo: video de máximo 5 minutos donde se presente resumidamente el trabajo de investigación (3 puntos)
**Actualización**: también existe la alterntiva de realizar un poster en lugar del video, los detalles para cada uno de los formatos en [este link](/docs/difusion-trabajos.html)

## Formato

- (R)Markdown: se recomienda su uso pues facilita la integración y reproducibilidad de los análisis en R.
  - Podrán encontrar una [guía básica para el uso de (R)Markdown](https://jciturras.github.io/Tutorial-rmarkdown/)
  - En sus **proyectos de RStudio Cloud** pondrán encontrar una plantilla para realizar el trabajo en este formato para el informe final (disponible próximamente aquí).

- Formato Tradicional: archivo .pdf en tamaño carta, letra Times New Roman, tamaño 12, interlineado 1,5, márgenes normales (2,5 cm superior e inferior, 3 cm derecho e izquierdo).

- Referencias: APA 6ta Edición o [ASA](https://www.asanet.org/sites/default/files/savvy/documents/teaching/pdfs/Quick_Tips_for_ASA_Style.pdf)

- Tablas de calidad: formato APA [(líneas horizontales y señalando fuente)](https://apastyle.apa.org/style-grammar-guidelines/tables-figures/tables).


## Fechas:

- Ver planificación

- Descuento por atraso: 0.5 por día corrido, luego de 3 días de atraso se da el trabajo por reprobado.

## Modalidad de entrega

En la sección de tareas de UCursos. Se debe adjuntar un archivo comprimido con los siguientes elementos:

1. Base de datos original y procesada

2. Código de preparación y de análisis

2. Documento del trabajo (que puede ser un archivo RMarkdown o Word)

El documento del trabajo debe ser ingresado además por **Turnitin**, se enviará link en la fecha de entrega para esto.


---

## Recomendaciones para el trabajo {.tabset}

### Escritura académica

- Una idea por párrafo

- Uso de "oración principal" (topic sentence): usualmente es la oración al principio del párrafo, que resume el sentido del párrafo completo y que conecta con el párrafo anterior.

- [Taller para escritura académica](https://es.scribd.com/document/454444052/Taller-para-escritura-academica)

- - [Publicación de artículos académicos: buenas prácticas y recomendaciones para la redacción y envío a revistas científicas](https://repositori.upf.edu/handle/10230/44599)

### A poner énfasis especialmente en informe 3

- el foco de este enforme es la aplicación de regresión múltiple como herramienta de análisis multivariado a un problema sustantivo de investigación. Por lo tanto, en el análisis se debe enfatizar qué sucede con los predictores en presencia de otros predictores, y en la argumentación esto se relaciona con qué sucede con mi factor explicativo central en presencia de otros factores explicativos

- en relación con lo anterior, se sugiere argumentar en base a una tesis central (ejemplo: influencia de educación en ingreso), luego agregar otros posibles factores explicativos que podrían estar afectando esta relación. No se recomienda presentar un "paquete" de factores explicativos (ej: cómo influye sexo, educación y edad en ingreso), sino jerarquizarlos.

- los conceptos centrales deben estar en las hipótesis y también luego operacionalizarse en variables. No presentar variables que no se relacionen con los conceptos centrales de la argumentación (a menos que solo sean variables de control).

- recordar que el control estadístico es algo que se aplica a todos los predictores del modelo, es decir, vía parcialización al ser una regresión múltiple. No confundir con "variables de control", que son variables que se pueden sumar al modelo sin necesidad de hipótesis sustantivas y por lo tanto sin un énfasis relevante en la interpretación.

- recordar que la tabla de univariados corresponde a sección de variables, no de análisis

- en la sección de metodología se debe presentar un apartado de _métodos_, donde se describa el método de estimación (ej: regresión múltiple por mínimos cuadrados ordinarios) así como la lógica de presentación de modelos

- si hay muchos casos perdidos (mas de un tercio de datos originales), explicar claramente a qué se debe esta pérdida. Existe la posiblidad de recuperar casos perdidos de predictores categóricos (o recodificados a categóricos) agregando una categoría adicional de perdidos. Esto se explica en la guía de [índices y transformación de variables](/assignment/11-code).


- interpretación de hipótesis e inferencia: las hipótesis nunca se comprueban o se descartan, solo se puede hablar de que existe o no existe evidencia a favor de la hipótesis planteada. Recordar: la ausencia de evidencia no es evidencia de ausencia.

- evitar términos técnicos estadísticos (ej: correlación ) antes de la sección de metodología

- existen algunas dificultades en el tratamiento de algunas variables como la de ingreso.

- mantener coherencia entre factores explicativos, hipótesis, descripción de variables, incorporación en el modelo, discusión, ojalá siempreen el mismo orden


regresión y N: cuántos casos son suficientes?

dicotomización de la dependiente para logística


### Ejemplos de artículos de investigación

- Con regresión simple

  - [Ortiz-Inostroza, C., & López, E. (2017). Explorando modelos estadísticos para explicar la participación en protestas en Chile. Revista de Sociología, (32), pp. 13-31. doi:10.5354/0719-529X.2017.47883](https://revistadesociologia.uchile.cl/index.php/RDS/article/view/47883/50542
)

  - [Cereceda-Marambio, K., & Torres-Solís, A. (2017). Satisfacción con la democracia en Chile: De lo normativo a lo valorativo. Revista de Sociología, (32), pp. 32-49. doi:10.5354/0719-529X.2017.47884] (https://revistadesociologia.uchile.cl/index.php/RDS/article/view/47884/50543)


- Con regresión logística

  - [Gayo Cal, M. G., Cabrol, G. O., & Méndez, M. L. (2019). Elección escolar y selección de familias: reproducción de la clase media alta en Santiago de Chile. Revista Internacional de Sociología, 77(1), 120. https://doi.org/10.3989/ris.2019.77.1.17.310](http://revintsociologia.revistas.csic.es/index.php/revintsociologia/article/view/1020/1338)

  - [Delfini, M. (2013) La afiliación sindical en Argentina. Análisis sobre sus determinantes. Revista Internacional de Sociología, 71(1)91-114,  http://dx.doi.org/10.3989/ris.2012.01.24.](http://revintsociologia.revistas.csic.es/index.php/revintsociologia/article/view/485/507)
