---
title: "Planificación"
slug: schedule
---

## Esta versión de la planificación corresponde a una recalendarización posterior a la toma y paro de Mayo-Junio 2022, la planificación original se puede revisar [aquí](/scheduleoriginal/)


Los dos componentes centrales del curso son las clases teóricas y las actividades prácticas.

- Las **clases** se realizarán los días **Viernes 8:30 - 11:45** en sala Julieta Kirkwood

- Las **prácticas** se realizarán los días **Miércoles 10:15 a 11:45** en sala de computación 21. En contexto post-paro el objetivo de este espacio es resolver dudas sobre las guías prácticas correspondientes a cada semana y sobre los contenidos del curso en general. Cada guía práctica puede ser desarrollada de manera autónoma y, además, se cuenta con el apoyo de video-cápsulas explicativas de los contenidos y códigos de R, las que estarán disponibles al final de la página de cada práctico.


| |<i class="fas fa-chalkboard-teacher"></i>  Clases  |  <i class="fas fa-user-edit"></i>  Prácticas y evaluaciones | <i class="fas fa-book-reader"></i> Lecturas y material adicional
-----|---------|-----------|-----------
<font color="orange"> **Marzo** </font> |   |   |
Viernes 18 | [**1. Presentación e introducción**](/class/01-class)  |  [Práctica 1: Preparación de datos](/assignment/01-code) | - Leer detalladamente [programa del curso](/programa) y también sobre la lógica de [clases y prácticos](/class)
Viernes 25 | [**2. Bases/Repaso**](/class/02-class) <br> - Datos y variables <br> - Preparación y descripción <br> - Varianza y covarianza <br> - Correlación (descriptiva)  |  [Práctica 2: Descripción de variables](/assignment/02-code)  | - [Lizon (2006) Estadística y causalidad en sociología](/docs/lecturas/Lizon 2006 Estadistica y causalidad en sociologia.pdf) <br> -  [Moore: 1.Comprensión de los datos (1-54)](/docs/lecturas/moore_comprensiondelosdatos.pdf)
<font color="orange"> **Abril** </font> |   |   |
Viernes 1 | [**3. Regresión simple I**](/class/03-class)  <br>- Distribución condicional<br> - Mínimos cuadrados y recta de regresión  | [Práctica 3: Correlación y regresión](/assignment/03-code) |- [Salgado (2009) Construyendo explicaciones en sociología](/docs/lecturas/salgado 2009 modelos sociologia.pdf)- <br> [Moore: 2. Análisis de relaciones (97-131)](/docs/lecturas/moore_analisisderelaciones1.pdf) <br>
Viernes 8 | [**4. Regresión simple II**](/class/04-class) <br> Regresión vs correlación <br> Residuos y ajuste general (R2)  |  [Practica 4: Residuos y ajuste](/assignment/04-code) |- [Linares (2018) Sociología y teoría social analíticas, cap. 2: La explicación en ciencias sociales](/docs/lecturas/linares 2018 Cap.2 Explicacion en sociologia.pdf) <br> - [Moore: Residuos (144-154)](/docs/lecturas/moore_residuos.pdf)
Viernes 15 | FERIADO |  |
Viernes 22    |   | [**Evaluación 1: Regresión simple (INDIVIDUAL)**]()  20% |   |
Viernes 29 | [**5. Regresión múltiple 1**](/class/05-class) <br> - Introducción   | [Práctica 5: Tabla de regresión múltiple y predictores categóricos](/assignment/05-code)  | - [Esser 2010 Sociología de las Variables](/docs/lecturas/Esser 2010 Sociología de las Variables.pdf) <br> - [Wooldridge (2010) Cap 3 (parcial): Análisis de regresión múltiple: estimación (68-80)](/docs/lecturas/Wooldridge_cap3estimacion.pdf)
<font color="orange"> **Mayo** </font> | **COMIENZO DEL PARO**   |   |
Viernes 6  |||
Viernes 13 |||
Viernes 20 |||
Viernes 27 |||
<font color="orange"> **Junio** </font> |   |   |
Viernes 3  |||
Viernes 10 |||
Viernes 17 |||
|   | **SE RETOMAN LAS ACTIVIDADES**  |
Viernes 24  | [**6. Regresión múltiple 2 y predictores categóricos**](/class/06-class) <br> - Coeficientes de regresión parcial <br>  - Correlación parcial y semiparcial <br>    | [Práctica 6: Parcialización y control estadístico](/assignment/06-code)  | - [Wooldridge (2010) Cap 3 (parcial): Análisis de regresión múltiple: estimación (68-80)](/docs/lecturas/Wooldridge_cap3estimacion.pdf)
<font color="orange"> **Julio** </font> |   |   |
Miércoles 29  |   | **Entrega informe avance trabajo grupal - 30%**: Regresión múltiple (informe grupal) <br> Dado el contexto de sobrecarga post-paro, la entrega de este informe es de carácter voluntario. Los grupos que entreguen en la fecha obtendrán una nota que equivale al 30% de la evaluación del curso y se les dará feedback para mejorar la entrega final. Quienes no lo entreguen se les corregirá solo el informe final y este tendrá un valor total de un  80% de la nota de presentación a examen.  |  - [Wooldridge (2010) Cap 19: Realización de un proyecto empírico (668-694)](/docs/lecturas/Wooldridge_19proyectoempirico.pdf)
Viernes 01| [**7. Regresión e inferencia**](/class/07-class) <br>- Conceptos y supuestos <br> - Tabla ANOVA <br> - Inferencia sobre coeficientes | [Práctica 7: Inferencia y reporte](/assignment/07-code) |- [Moore 7: Inferencia para medias (482-543)](/docs/lecturas/Moore_inferencia_medias.pdf) |
Viernes 08 - Primer Bloque | [**8. Regresión logística  I**](/class/09-class) <br> - Probabilidades <br>- Odds ratios   | [Práctica 8: Probabilidades y Odds](/assignment/09-code) | [Camarero et al (2017) Regresión logística (1-29)](/docs/lecturas/Camarero_Odd_Ratio_LogitV2.pdf) <br>
Viernes 08 - Segundo Bloque| [**9. Regresión logística II**](/class/10-class) <br>- Estimación de parámetros <br>- Inferencia <br>- Predicción | [Práctica 9: Estimación logística](/assignment/10-code)  | - [Camarero et al (2017) Regresión logística (30-52)](/docs/lecturas/Camarero_Odd_Ratio_LogitV2.pdf)
Viernes 15 | [**10. Supuestos y chequeos de robustez**](/class/11-class) <br> - Relaciones no lineales <br> -Transformaciones <br> - Centrado | [Práctica 10: Transformación de variables y supuestos de regresión](/assignment/11-code)  | -   [Darlington & Hayes 2016 Cap16 Detecting and Managing Irregularities](/docs/lecturas/Darlington&Hayes_16irregularities.pdf) <br> - [Darlington & Hayes 2016 Cap12 Nonlinear relationships](/docs/lecturas/Darlington&Hayes_13nonlinear.pdf) <br> - [Wooldridge cap 6 Temas adicionales](/docs/lecturas/Wooldridge_6temasadicionales.pdf)
Viernes 22 |  | **Informe Final 50%** : Regresión logística y predictores categóricos <br>  **Ponderación:** si no se entregó el informe de avance, su ponderación se sumará a esta nota y será **80%**  |
<font color="orange"> **Agosto** </font> |   |   |
Viernes 5|   | **Examen Final**: Toda la materia (incluido supuestos y chequeos de robustez, aún cuando este tema no se evalúa en el trabajo)  |
