---
title: Programa
slug: programa
citeproc: true
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
      toc: TRUE
---

[^courseinfo]: {-}
  `r blogdown::shortcode("courseinfo")`

## Concepto del curso

a) A pesar de su nombre, este no es un curso de (mera) estadística. Es un curso que enseña algunas técnicas de análisis cuantitativo orientadas al **contraste empírico de teoría sociológica**, para lo cual se vale de técnicas estadísticas como la regresión múltiple. En este contexto, los métodos son considerados funcionales a preocupaciones sustantivas y relevantes del mundo social

b) Además de las herramientas de análisis, el curso pone también énfasis en el **reporte y comunicación de resultados**. Los análisis de datos son siempre realizados en relación a otr_s, quienes tienen ser capaz de entender lo que se está presentando. Este aspecto se relaciona con tener en cuenta la relevancia y aporte del conocimiento científico en temas sociales.

c) Un tercer énfasis transversal en el curso es la **apertura del proceso de investigación**. Para poder realizar investigación de manera eficiente y generativa es importante no "reinventar la rueda", preocupándose de que nuestros análisis sean comprensibles para los demás (y para nosotr_s en el futuro). Por ello utilizamos programas de análisis de código abierto (como R) y promovemos que los códigos de análisis sean reproducibles.

## Propósito general del curso

Al finalizar el curso los estudiantes conocerán los fundamentos del análisis estadístico multivariado.

Se espera que los estudiantes sean capaces de:

- identificar las principales técnicas de análisis estadístico multivariado utilizadas en la investigación sociológica

- depurar y preparar datos para la aplicación de distintas técnicas de análisis estadístico multivariado; corroborar las condiciones de aplicación de distintas técnicas de análisis estadístico multivariado

- utilizar  software de análisis estadístico

- contrastar hipótesis de investigación

- elaborar reportes de resultados y conclusiones a partir de la aplicación de diferentes técnicas de análisis estadístico multivariado.

Complementariamente se espera que los estudiantes adquieran herramientas que les permitan comunicar resultados de investigación en contextos sociales, profesionales y académicos.

## Competencias a las que contribuye el curso

- Diseñar y desarrollar estrategias de investigación social.

- Comunicar los saberes disciplinares de manera pertinente a las características de distintos contextos y audiencias, utilizando diversas estrategias y formatos.

### Sub-Competencias

- Diseñar y aplicar diversas técnicas de recolección y producción de información empírica, pertinentes al objeto de estudio.

-  Interpretar información empírica aplicando diversas técnicas, en función de un plan de análisis.

- Diseñar estrategias para comunicar los saberes disciplinares considerando las características de distintos contextos y audiencias.

- Comunicar en forma oral y escrita los saberes disciplinares considerando distintos contextos y audiencias, haciendo un uso creativo de distintas estrategias.

## Resultados de Aprendizaje

Al finalizar el curso, los estudiantes:

- Serán capaces de explicar los conceptos y fundamentos teóricos y estadísticos de la investigación social basada en modelos predictivos para variables observadas y serán capaces de explicar su utilidad para la sociología.

- Serán capaces de preparar y depurar bases de datos para su análisis utilizando técnicas multivariadas, evaluando la pertinencia y la presencia de condiciones para la aplicación de modelos predictivos para variables observadas.

- Serán capaces de manejar software especializado y reportar los resultados de modelos predictivos para variables observadas cuantitativas y no cuantitativas.

## Saberes / contenidos

### UNIDAD 1: Introducción al modelamiento de datos sociales

- Tipos de investigación (descriptiva vs relacional y explicativa) y su materialización en el análisis estadístico.
- La explicación en ciencias sociales: su relación con el concepto de covariación; la explicación como dependencia robusta y como cadena causal y el trabajo con modelos.
- El trabajo con modelos: tipos de modelos (modelo teórico, modelo normativo, modelo científico, modelo estadístico); la vinculación entre los modelos científicos y los modelos teóricos; los modelos estadísticos como tipo de modelo científico.
- Ciencia abierta y modelamiento: transparencia, reproducibilidad y replicación.

### UNIDAD 2: Regresión Lineal Simple y Múltiple

- Bases: varianza, covarianza y correlación.
- Usos y aplicaciones en ciencias sociales de la regresión lineal.
- Supuestos y condiciones de aplicación de la regresión lineal.
- Manejo de casos influyentes
- Procedimientos de estimación e interpretación de parámetros.
- Introducción de variables de control estadístico.
- Criterios de validez, capacidad predictiva y evaluación del ajuste de la regresión lineal.
- Temas avanzados de regresión lineal: introducción de predictores categóricos, estimación de efectos de interacción y mediación, y uso de herramientas gráficas como apoyo a la interpretación y análisis de datos.

### UNIDAD 3: Regresión múltiple para variables dependientes categóricas

- Limitaciones de la regresión lineal y potencialidades de la introducción de variables dependientes categóricas.
- Concepto y sentido de la función logística y funciones afines.
- Supuestos y condiciones de aplicación de la regresión para variables categóricas.
- Procedimientos de estimación e interpretación de parámetros de regresión logística.
- Criterios de validez, capacidad predictiva y evaluación del ajuste de la regresión Logística.
- Generalización de modelos de regresión logística: modelo de regresión logística multinomial y ordinal.
- Empleo de otras matrices de correlación (tetracórica, biserial y policórica).

## Metodología

En las circunstancias excepcionales de este semestre dada la crisis sanitaria, se han realizado una serie de ajustes metodológicos. En este contexto, tendremos tres espacios principales de aprendizaje:

1. **Sesiones de clases lectivas**, donde se presentarán los aspectos centrales de los contenidos correspondientes a la semana. Tanto el documento de presentación como el video de la clase se encontrará disponible en la pestaña de [Contenidos](/class/) de este sitio.

2. **Prácticos**: cada tema de las sesiones se acompaña de una _guía práctica_ de aplicación de contenidos. Estas guías están diseñadas para ser desarrolladas de manera autónoma por cada estudiante semana a semana. También serán desarrolladas y revisadas cada semana en grupos pequeños con supervisión de ayudantes para dar mayor oportunidad de participación y resolver las dudas respectivas. Existe un reporte de progreso asociado a estas guías que deberá ser completado semanalmente con fines de monitoreo y retroalimentación.

3. **Trabajos**: se desarrollarán trabajos de investigación durante el semestre (ver sección evaluación abajo) que permitirán a l_s participantes aplicar contenidos y recibir retroalimentación de su desempeño. Los trabajos serán asesorados principalmente por ayudantes que se asignarán a cada grupo.

## Evaluación (detalles en pestaña [Trabajos](/reference/))

El curso tendrá tres instancias de evaluación:

- **Evaluación 1** (individual): Correlación y regresión simple (20%).
- **Evaluación 2** (trabajo grupal): Regresión multiple e inferencia estadística (30%)
- **Evaluacion 3** (trabajo grupal): Regresión logística, predictores categóricos y supuestos (50%)

La nota ponderada de los trabajos equivaldrá al 60% de la nota del curso y el examen final al 40% restante.

En el caso de los trabajos, en caso de atraso se descontará 0.5 por día adicional. Si el trabajo no se entrega luego del tercer día de atraso será calificado con nota 1.0

Los justificativos por ausencia o atraso se realizan en la secretaría de carrera.

## Requisitos de aprobación

Nota mínima de aprobación: 4,0 (en escala de 1 a 7).

Requisitos de eximición de examen:

1. contar con un promedio ponderado igual o superior a 5.0
2. no tener nota bajo 4 en ninguna de las evaluaciones

Requisitos para presentación a examen:

- Podrán presentarse al examen de primera oportunidad los estudiantes que hayan obtenido una calificación final igual o superior a 3.5.

- El examen de segunda oportunidad será para aquellos estudiantes que presenten una nota igual o inferior a 3.5 o aquellos que en el examen de primera oportunidad no hubiesen logrado una nota igual o superior a 4.0.

## Bibliografía

La bibliografía obligatoria para cada semana está disponible en la [planificación del curso](/schedule/), desde donde se puede acceder directamente a los documentos. De todas maneras, abajo algunos textos comentados y referencias para cada unidad.

### Textos principales.

Hay cuatro referencias principales recomendadas para este curso:

- **Moore (2010) Estadística aplicada básica. Barcelona: Antoni Bosch**. Explica de manera bastante clara (y en español) una serie de análisis estadísticos que sirven de base para este curso.

- **Darlington, R. B., & Hayes, A. F. (2017). Regression analysis and linear models: concepts, applications, and implementation. Guilford Press.** Este libro me parece un muy buen texto para acompañar un curso de regresión en ciencias sociales, lamentablemente está en inglés y por lo tanto solo es bibliografía sugerida.

- **Wooldridge, J. M. (2008). Introducción a la econometría: un enfoque moderno. Paraninfo Cengage Learning.** Libro clásico de regresión para economistas, la ventaja es que está en español, la desventaja (para nosotros) es que en ocasiones utiliza un lenguaje y ejemplos lejanos a la sociología.

- **Wickham, H., & Grolemund, G. (2016). R for data science: import, tidy, transform, visualize, and model data (First edition). Sebastopol: O’Reilly.** Libro con enfoque en el aprendizaje de R con técnicas que ciertamente van más allá del curso, pero muy util como referencia general. Además, está disponible también en español como ["R para ciencia de datos"](https://es.r4ds.hadley.nz/).

**Abajo bilbiografía recomendada para cada unidad**


### MODELOS CIENTÍFICOS (Unidad 1)

- García-Ferrando, M. (1985). Análisis y modelización causal en sociología. Reis, 29(1), 143-164.
- Goldthorpe, J. H. (2001). Causation, statistics, and sociology. European Sociological Review, 17(1), 1-20.
- Ramón, L., & Ángeles, M. (2006). Estadística y causalidad en la sociología empírica del XX. Papers: revista de sociología, 80(1), 223-255.
- Salgado, M. (2009). Construyendo explicaciones: el uso de modelos en sociología. Persona y Sociedad, 30 (3), 29-60.

### MODELOS DE REGRESIÓN LINEAL (Unidad 2)
- Etxeberria, J. (1999). Regresión múltiple. Madrid: La Muralla.
- Fox, J. & Weisberg, S. (2011) An R Companion to Applied Regression (149-183). London: Sage.
- Pértega-Díaz, S., & Pita-Fernández, S. (2000). Técnicas de regresión: Regresión lineal múltiple. Cuadernos de atención primaria, 7(3), 173-176. En: https://dialnet.unirioja.es/servlet/articulo?codigo=2331162
- Pértega-Díaz, S., & Pita-Fernández, S. (2000). Técnicas de regresión: Regresión lineal simple. Cuadernos de atención primaria, 7(2), 91-94. En: https://dialnet.unirioja.es/servlet/articulo?codigo=2331559
- Grolemund, G. & Wickam, H. (2017) R for Data Science. Disponible en: https://r4ds.had.co.nz/

### MODELOS DE REGRESIÓN PARA VARIABLES CATEGÓRICAS (Unidad 3)
- Silva LC, Barroso J. (2004). Regresión Logística. Cuaderno 27. Madrid: La Muralla.
- Silva LC. (1995). Excursión a la regresión logística en ciencias de la salud. Madrid: Díaz de Santos; 1995.
- Jovell, A.J. (1995). Análisis de regresión logística, Cuadernos Metodológicos del CIS. Madrid.

### Links & otras recomendaciones

- [Econometrics with R](https://www.econometrics-with-r.org/6-2-tmrm.html)


## Software

Usaremos R 4.1 a través de la interfaz de RStudio. También realizaremos ejercicios y prácticas online en RCloud.

## Plataformas de comunicación y discusión

- Foros Ucursos
- Disqus

## VARIOS

- Las clases en general se acompañan de documentos de presentación, que estarán disponibles antes de la sesión en la página de [Materiales](/class/), y están desarrollados con base en Rmarkdown/XaringanRmarkdown/ Xaringan. Estos documentos no son:

  - “la clase”
  - autoexplicativos (ni aspiran a serlo)
  - “el ppt” (ni mucho menos “la ppt”)

- **Políticas de participación y trato**: se espera y enfatiza la participación por distintos canales disponibles. También se enfatiza un trato respetuoso y horizontal. Quienes están tomando este curso serán referidos como participantes y/o estudiantes, evitar el uso de "l_s cabr_s" o "l_s chiquill_s". Quien no se sienta tratad_ apropiadamente o vea que otr_s no lo estan siendo, se solicita reportar para solucionar la situación.


## Programación de sesiones

Visitar la página de [Planificación](/schedule/).
