---
title: Trabajos
slug: trabajos
output:
  blogdown::html_page:
      toc: TRUE
---

El curso tendrá tres instancias de evaluación (fechas en pestaña de [planificación](/schedule)):

- **Prueba 1** (individual): Correlación y regresión simple (20%).
- **Trabajo grupal (máximo 5 integrantes)**
  - entrega 1 avance: regresión multiple e inferencia estadística (30%).
  - entrega 2 final:  + regresión logística, predictores categóricos, supuestos (50%).

La nota ponderada de las evaluaciones equivaldrá al 60% de la nota del curso y el examen final al 40% restante.

# Pauta de trabajo grupal

## Objetivo general

Aplicar los contenidos del curso a una temática de interés en formato de artículo de investigación breve.

## Sobre los temas y datos

De modo de lograr una mayor colaboración desde el equipo docente a sus trabajos, sugerimos desarrollar los siguientes temas:

- Desigualdad social, educación cívica, justicia distributiva, opinión pública
- Estratificación social, política educativa, sociología política
- Economía laboral, relaciones laborales, acción colectiva y condiciones de empleo

Los datos a utilizar corresponden a bases de datos secundarias que coincidan con los temas de interés del grupo. Algunas sugeridas son:

- [Encuesta bienestar social MIDESOC](http://observatorio.ministeriodesarrollosocial.gob.cl/encuesta-bienestar-social)
- [ELSOC](https://coes.cl/encuesta-panel/) (Ola 1)
- [CASEN](http://observatorio.ministeriodesarrollosocial.gob.cl/encuesta-casen-2017) (evt. subset)
- [SIMCE](https://informacionestadistica.agenciaeducacion.cl/#/bases) (evt. subset)
- [LAPOP](https://www.vanderbilt.edu/lapop-espanol/)
- [Desiguales](https://www.desiguales.org/descripcin-del-libro)
- [CEP 83 -  Módulo Desigualdad Social ISSP 2019](https://www.cepchile.cl/cep/encuestas-cep/encuestas-2009-2018/estudio-nacional-de-opinion-publica-mayo-2019)
- [CEP: varios temas/preguntas para encuestas desde 1990 en adelante, muy buen buscador!](https://www.cepchile.cl/cep/site/edic/base/port/buscador.html)
- ISSP (International Social Survey Programme)
  - [Desigualdad Social](https://www.gesis.org/issp/modules/issp-modules-by-topic/social-inequality)
  - [Rol del Gobierno](https://www.gesis.org/en/issp/modules/issp-modules-by-topic/role-of-government)
  - [Orientaciones del trabajo](https://www.gesis.org/issp/modules/issp-modules-by-topic/work-orientations/2015)
- [ICTWSS](http://uva-aias.net/en/ictwss)
- Encuestas Laborales
  - [ENE](http://bancodatosene.ine.cl/)
  - [ESI](https://www.ine.cl/estadisticas/sociales/ingresos-y-gastos/encuesta-suplementaria-de-ingresos)
  - [ENUT](https://www.ine.cl/estadisticas/sociales/genero/uso-del-tiempo)

## Modalidad de trabajo y asesorías

- **Inscripción de temas**
  - Debe realizarse a principios de Mayo vía **U-Cursos**
  - El documento debe indicar claramente integrantes, correo, tema y base de datos a utilizar

- Se asignará un ayudante y apoyo docente a cada grupo, quienes tendrán la oportunidad de contar con asesorías semanales


## Entregas

Este trabajo posee dos entregas, tal como se señala en el programa del curso

- **Entrega 1 (avance)**: se presenta un avance de la temática general a abordar así como también datos y variables en la sección de métodos, análisis descriptivos y estimación con regresión . El énfasis en esta primera entrega se encuentra en el planteamiento de las hipótesis y el modelo de regresión asociado. Incluye estimar el modelo de regresión múltiple y su  interpretación (total máximo 2000 palabras)

  - Consideraciones: En el caso de los trabajos donde la variable dependiente sea categórica dicotómica (ej: fuma 1=si, 0=no), para esta primera entrega la estimación puede ser realizada preliminarmente como regresión lineal, y para la segunda se espera estimación con regresión logística


- **Entrega 2 (final)**: Su formato es de artículo/ reporte breve de investigación. En esta entrega se corrigen aspectos de la **Entrega 1**, junto con profundizar en el chequeo de supuestos y casos influyentes. Aquellos grupos que trabajen con una variable dependiente continua deberán realizar además al menos una estimación de regresión logística (y su correspondiente interpretación) con la variable dependiente dicotomizada (total máximo 3.000 palabras). Se debe incluir al menos un predictor categórico.

## Secciones del trabajo

- Título: Breve, lo principal es hacer alusión al objeto central de estudio (variable dependiente) (0,5 pto)

- Resumen/Abstract (250 palabras), incluye: problema/pregunta, objetivo, datos (y N), resultado principal. (0,5 pto)

1. Introducción: definición de la problemática a abordar, su relevancia y principales conceptos (500 palabras). (1 punto)

- En este apartado es importante considerar:

  - Relevancia del problema de investigación: además de que el "tema" pueda ser relevante (ej: aumento de desigualdad económica, disminución de niveles de participación), la relevancia del problema se refiere al aporte distintivo desde una perspectiva académica y disciplinar (sociología) (ej: "existe evidencia que los bajos niveles de participación se ven afectados por el nivel educacional (Pérez, 1999").
  - Precisar el concepto central que se va a investigar: Ejemplo "vamos a estudiar participación informal, entendiendo por ello la frecuencia de participación en actividades como marchas, boycotts y en redes sociales".
  - Precisar argumento / hipótesis central, que tiene que ver con el predictor principal: "proponemos que a medida que aumenta el nivel de contactos con identificación política de izquierda, aumenta la participación política informal"


2. Antecedentes conceptuales y empíricos (2p)

    - Una primera sub-sección corresponde al objeto central de estudio o explanandum (variable dependiente), donde se profundiza en su origen y definición, y se revisan las principales investigaciones que se asocian a este concepto. (**+/-** 4 referencias). Ej: "2.1 Participación política informal"

    - El segundo apartado corresponde a los conceptos que intentan explicar las variaciones en el objeto de estudio o explanans (variables independientes, al menos 3), y en los cuales se basan las hipótesis (Ej: "2.2 Factores asociados a la participación política informal"). Se revisan en orden de relevancia, comenzando por el que está en el argumento central, y luego se van agregando conceptos secundarios y sus hipótesis correspondientes (al menos dos referencias por cada concepto explicativo).  Ejemplo de argumento(s) secundario(s) asociados a otros conceptos relevantes: "Además se considerará en qué medida el nivel educacional se asocia a la participación política informal". Y también añadir argumentos de control: "Dado que el nivel educacional se podría asociar positivamente con el nivel de contactos, el efecto de los contactos en participación política informal disminuirá al controlar por nivel educacional"

3. Objetivos / hipótesis (un objetivo e hipótesis por cada variable independiente) (250 palabras). Ej: "a medida que aumenta el nivel educacional, aumenta la participación política informal" (1 punto)

4. Metodología (3 puntos, uno por cada subsección):

    4.1 Datos (no olvidar número de casos)

    4.2 Variables: Esta sección también incluye una tabla de descriptivos básicos, y una descripción detallada de la operacionalización y medición de las variables.
    - **Sobre la operacionalización de la variable dependiente**: por definición la variable dependiente en regresión múltiple OLS es continua. Escalas tipo likert pueden ser utilizadas en casos justificados y también teniendo en cuenta su variabilidad (si muchos casos se acumulan en pocas categorías la varianza va a ser pequeña, menos posibilidades de covarianza, y por tanto baja probabilidad de encontrar efectos significativos).

    4.3 Métodos: descripción breve del método de regresión a utilizar y lógica de presentación de los modelos

5. Análisis (1500 palabras) (4 puntos entrega 1, 8 puntos entrega 2)

    5.1 Análisis descriptivo: tablas o gráficos bivariados según sea más pertinente, al menos uno por cada variable independiente (1 punto)

    5.2 Modelos de regresión: presentación de tabla(s) y descripción de cada modelo y sus coeficientes principales, interpretando en términos de tamaño como así también significación estadística y ajuste global del modelo (R2). Hacer referencia a cada hipótesis al momento de analizar los coeficientes. (2 puntos)

  - se deben adjuntar además las hojas de código de preparación (0,5p), análisis (0,5p) y la base de datos.

- Bibliografía

---

Las siguientes secciones se evaluarán solo en la entrega 2

6. Conclusiones, con énfasis en la relación entre variable dependiente e independientes, limitaciones, posibles investigaciones futuras. (300 palabras) (2 puntos)


## Formato

- Formato Tradicional: archivo .pdf en tamaño carta o A4, letra Times New Roman, tamaño 12, interlineado 1,5, márgenes normales (2,5 cm superior e inferior, 3 cm derecho e izquierdo).

- (R)Markdown: se recomienda su uso pues facilita la integración y reproducibilidad de los análisis en R.

  - Podrán encontrar una [guía básica para el uso de (R)Markdown](https://jciturras.github.io/tutorial-rmarkdown/)

  - Plantilla para realizar el trabajo en RMarkdown para el informe final (disponible próximamente aquí).

- Referencias: APA 6ta Edición o [ASA](https://www.asanet.org/sites/default/files/savvy/documents/teaching/pdfs/Quick_Tips_for_ASA_Style.pdf)

- Tablas de calidad: orientarse por formato APA [(líneas horizontales y señalando fuente)](https://apastyle.apa.org/style-grammar-guidelines/tables-figures/tables).

## Modalidad de entrega

En la sección de tareas de UCursos. Se debe adjuntar un archivo comprimido con los siguientes elementos:

1. Base de datos original y procesada

2. Código de preparación y de análisis

2. Documento del trabajo (que puede ser un archivo RMarkdown o Word)

El documento del trabajo debe ser ingresado además por **Turnitin**, se enviará link en la fecha de entrega para esto.


---

## Recomendaciones para el trabajo {.tabset}

### Escritura académica

- Una idea por párrafo

- Uso de "oración principal" (topic sentence): usualmente es la oración al principio del párrafo, que resume el sentido del párrafo completo y que conecta con el párrafo anterior.

- [Taller para escritura académica](https://es.scribd.com/document/454444052/Taller-para-escritura-academica)

- [Publicación de artículos académicos: buenas prácticas y recomendaciones para la redacción y envío a revistas científicas](https://repositori.upf.edu/handle/10230/44599)

### A poner énfasis especialmente en informe 2

- el foco de este enforme es la aplicación de regresión múltiple como herramienta de análisis multivariado a un problema sustantivo de investigación. Por lo tanto, en el análisis se debe enfatizar qué sucede con los predictores en presencia de otros predictores, y en la argumentación esto se relaciona con qué sucede con mi factor explicativo central en presencia de otros factores explicativos

- en relación con lo anterior, se sugiere argumentar en base a una tesis central (ejemplo: influencia de educación en ingreso), luego agregar otros posibles factores explicativos que podrían estar afectando esta relación. No se recomienda presentar un "paquete" de factores explicativos (ej: cómo influye sexo, educación y edad en ingreso), sino jerarquizarlos.

- los conceptos centrales deben estar en las hipótesis y también luego operacionalizarse en variables. No presentar variables que no se relacionen con los conceptos centrales de la argumentación (a menos que solo sean variables de control).

- recordar que el control estadístico es algo que se aplica a todos los predictores del modelo, es decir, vía parcialización al ser una regresión múltiple. No confundir con "variables de control", que son variables que se pueden sumar al modelo sin necesidad de hipótesis sustantivas y por lo tanto sin un énfasis relevante en la interpretación.

- recordar que la tabla de univariados corresponde a sección de variables, no de análisis

- en la sección de metodología se debe presentar un apartado de _métodos_, donde se describa el método de estimación (ej: regresión múltiple por mínimos cuadrados ordinarios) así como la lógica de presentación de modelos

- si hay muchos casos perdidos (mas de un tercio de datos originales), explicar claramente a qué se debe esta pérdida. Existe la posiblidad de recuperar casos perdidos de predictores categóricos (o recodificados a categóricos) agregando una categoría adicional de perdidos. Esto se explica en la guía de [índices y transformación de variables](/assignment/11-code).


- interpretación de hipótesis e inferencia: las hipótesis nunca se comprueban o se descartan, solo se puede hablar de que existe o no existe evidencia a favor de la hipótesis planteada. Recordar: la ausencia de evidencia no es evidencia de ausencia.

- evitar términos técnicos estadísticos (ej: correlación ) antes de la sección de metodología

- existen algunas dificultades en el tratamiento de algunas variables como la de ingreso.

- mantener coherencia entre factores explicativos, hipótesis, descripción de variables, incorporación en el modelo, discusión, ojalá siempre en el mismo orden



### Ejemplos de artículos de investigación

- Con regresión simple

  - [Ortiz-Inostroza, C., & López, E. (2017). Explorando modelos estadísticos para explicar la participación en protestas en Chile. Revista de Sociología, (32), pp. 13-31. doi:10.5354/0719-529X.2017.47883](https://revistadesociologia.uchile.cl/index.php/RDS/article/view/47883/50542
)

  - [Cereceda-Marambio, K., & Torres-Solís, A. (2017). Satisfacción con la democracia en Chile: De lo normativo a lo valorativo. Revista de Sociología, (32), pp. 32-49. doi:10.5354/0719-529X.2017.47884] (https://revistadesociologia.uchile.cl/index.php/RDS/article/view/47884/50543)


- Con regresión logística

  - [Gayo Cal, M. G., Cabrol, G. O., & Méndez, M. L. (2019). Elección escolar y selección de familias: reproducción de la clase media alta en Santiago de Chile. Revista Internacional de Sociología, 77(1), 120. https://doi.org/10.3989/ris.2019.77.1.17.310](http://revintsociologia.revistas.csic.es/index.php/revintsociologia/article/view/1020/1338)

  - [Delfini, M. (2013) La afiliación sindical en Argentina. Análisis sobre sus determinantes. Revista Internacional de Sociología, 71(1)91-114,  http://dx.doi.org/10.3989/ris.2012.01.24.](http://revintsociologia.revistas.csic.es/index.php/revintsociologia/article/view/485/507)
