<!DOCTYPE html>
<html lang="en-us" 
      xmlns:og="http://ogp.me/ns#" 
      xmlns:fb="https://www.facebook.com/2008/fbml">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.7.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Juan Castillo">

  
  
  
    
  
  <meta name="description" content="a.sourceLine { display: inline-block; line-height: 1.25; } a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; } a.sourceLine:empty { height: 1.2em; } .sourceCode { overflow: visible; } code.sourceCode { white-space: pre; position: relative; } div.sourceCode { margin: 1em 0; } pre.sourceCode { margin: 0; } @media screen { div.sourceCode { overflow: auto; } } @media print { code.sourceCode { white-space: pre-wrap; } a.sourceLine { text-indent: -1em; padding-left: 1em; } } pre.">

  
  <link rel="alternate" hreflang="en-us" href="/assignment/10-code/">

  


  
  
  
  <meta name="theme-color" content="#CF4446">
  

  
  
  
  <script src="/js/mathjax-config.js"></script>
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    

  

  
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400i&display=swap">
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  




  


  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/images/icon_hu1d2581101f943b2ec717907f12f16034_15667_32x32_fill_lanczos_center_2.png">
  <link rel="apple-touch-icon" type="image/png" href="/images/icon_hu1d2581101f943b2ec717907f12f16034_15667_192x192_fill_lanczos_center_2.png">

  <link rel="canonical" href="/assignment/10-code/">

  
  
  
  
  
    
  
  
  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@juankcastillo">
  <meta property="twitter:creator" content="@juankcastillo">
  
  <meta property="og:site_name" content="Estadística Multivariada">
  <meta property="og:url" content="/assignment/10-code/">
  <meta property="og:title" content="Práctica 10: Regresión Logística 2 | Estadística Multivariada">
  <meta property="og:description" content="a.sourceLine { display: inline-block; line-height: 1.25; } a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; } a.sourceLine:empty { height: 1.2em; } .sourceCode { overflow: visible; } code.sourceCode { white-space: pre; position: relative; } div.sourceCode { margin: 1em 0; } pre.sourceCode { margin: 0; } @media screen { div.sourceCode { overflow: auto; } } @media print { code.sourceCode { white-space: pre-wrap; } a.sourceLine { text-indent: -1em; padding-left: 1em; } } pre."><meta property="og:image" content="/img/social-image.png">
  <meta property="twitter:image" content="/img/social-image.png"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2020-08-14T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2020-08-10T22:57:39-04:00">
  

  



  


  


  <link rel="shortcut icon" href="/favicon.ico" />
  <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/img/apple-touch-icon-57x57.png" />
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/img/apple-touch-icon-114x114.png" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/img/apple-touch-icon-72x72.png" />
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/img/apple-touch-icon-144x144.png" />
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/img/apple-touch-icon-120x120.png" />
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/img/apple-touch-icon-152x152.png" />
  <link rel="icon" type="image/png" href="/img/favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="/img/favicon-16x16.png" sizes="16x16" />
  <meta name="application-name" content="SOC 01024: Estadística Multivariada" />
  <meta name="msapplication-TileColor" content="#FFFFFF" />
  <meta name="msapplication-TileImage" content="/img/mstile-144x144.png" />


  <title>Práctica 10: Regresión Logística 2 | Estadística Multivariada</title>

</head>


<body id="top" data-spy="scroll" data-offset="70"
    data-target="#TableOfContents"
    >

    <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


    







<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">Estadística Multivariada</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">Estadística Multivariada</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-end" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/programa/"><span>Programa</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/schedule/"><span>Planificación</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/class/"><span>Material</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/reference/"><span>Trabajos</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/tutorial/"><span>RStudio.cloud</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">
      

      

      

    </ul>

  </div>
</nav>


    

<div class="container-fluid docs">
    <div class="row flex-xl-nowrap">
        <div class="col-12 col-md-3 col-xl-2 docs-sidebar">
            





  




<form class="docs-search d-flex align-items-center">
  <button class="btn docs-toggle d-md-none p-0 mr-3" type="button" data-toggle="collapse" data-target="#docs-nav" aria-controls="docs-nav" aria-expanded="false" aria-label="Toggle section navigation">
    <span><i class="fas fa-bars"></i></span>
  </button>

  
</form>

<nav class="collapse docs-links" id="docs-nav">
  

  
  
  
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/class/01-class/">Contenidos</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/class/01-class/">1: Presentación</a>
      </li>
      
      <li >
        <a href="/class/02-class/">2: Bases</a>
      </li>
      
      <li >
        <a href="/class/03-class/">3: Regresión simple 1</a>
      </li>
      
      <li >
        <a href="/class/04-class/">4: Regresión simple 2</a>
      </li>
      
      <li >
        <a href="/class/05-class/">5: Regresión múltiple 1</a>
      </li>
      
      <li >
        <a href="/class/06-class/">6: Regresión múltiple 2</a>
      </li>
      
      <li >
        <a href="/class/07-class/">7: Categóricos / inferencia (1)</a>
      </li>
      
      <li >
        <a href="/class/08-class/">8: Inferencia (2)</a>
      </li>
      
      <li >
        <a href="/class/09-class/">9: Logística (1)</a>
      </li>
      
      <li >
        <a href="/class/10-class/">10: Logística (2)</a>
      </li>
      
      <li >
        <a href="/class/11-class/">11: Supuestos</a>
      </li>
      
    </ul>
    

  </div>
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/assignment/01-code/">Practicas</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/assignment/01-code/">Práctica 1: Preparación datos</a>
      </li>
      
      <li >
        <a href="/assignment/02-code/">Práctica 2: Descripción de variables</a>
      </li>
      
      <li >
        <a href="/assignment/03-code/">Práctica 3: Regresión simple 1</a>
      </li>
      
      <li >
        <a href="/assignment/04-code/">Práctica 4: Regresión simple 2</a>
      </li>
      
      <li >
        <a href="/assignment/05-code/">Práctica 5: Regresión múltiple 1</a>
      </li>
      
      <li >
        <a href="/assignment/06-code/">Práctica 6: Regresión múltiple 2</a>
      </li>
      
      <li >
        <a href="/assignment/07-code/">Práctica 7. Inferencia y predictores categóricos</a>
      </li>
      
      <li >
        <a href="/assignment/08-code/">Práctica 8. Tabla de regresión múltiple</a>
      </li>
      
      <li >
        <a href="/assignment/09-code/">Práctica 9. Regresión Logística 1</a>
      </li>
      
      <li class="active">
        <a href="/assignment/10-code/">Práctica 10: Regresión Logística 2</a>
      </li>
      
    </ul>
    

  </div>
  
  
</nav>

        </div>

        

        <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 docs-content" role="main">

            <article class="article">

                <div class="docs-article-container">
                    <h1>Práctica 10: Regresión Logística 2</h1>

                    

                    

                    
                    <div class="due-date p-2 mb-3 bg-secondary text-white">
                        Materiales de la sesión del 07 Aug 2020
                    </div>
                    

                    <div class="article-style">
                        
<!-- BLOGDOWN-HEAD -->
<script src="/rmarkdown-libs/clipboard/clipboard.min.js"></script>
<link href="/rmarkdown-libs/primer-tooltips/build.css" rel="stylesheet" />
<link href="/rmarkdown-libs/klippy/css/klippy.min.css" rel="stylesheet" />
<script src="/rmarkdown-libs/klippy/js/klippy.min.js"></script>
<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  { background-color: #f8f8f8; }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>
<!-- /BLOGDOWN-HEAD -->

<h2>Índice</h2>
<div id="TOC">
<ul>
<li><a href="#objetivo">Objetivo</a></li>
<li><a href="#librerías">Librerías</a></li>
<li><a href="#datos">Datos</a><ul>
<li><a href="#explorar-datos">Explorar datos</a></li>
</ul></li>
<li><a href="#estimación">Estimación</a><ul>
<li><a href="#presentación-de-resultados">Presentación de resultados</a></li>
<li><a href="#tabla-de-regresión">Tabla de regresión</a><ul>
<li><a href="#regresión-logística-sin-predictores">Regresión logística sin predictores</a></li>
<li><a href="#regresión-logistica-con-variable-binaria-como-predictor">Regresión logistica con variable binaria como predictor</a></li>
<li><a href="#regresión-logística-con-variable-continua-como-predictor">Regresión logística con variable continua como predictor</a></li>
<li><a href="#regresión-logística-con-múltiples-predictores">Regresión logística con múltiples predictores</a></li>
</ul></li>
</ul></li>
<li><a href="#medidas-de-ajuste">Medidas de Ajuste</a><ul>
<li><a href="#test-de-devianza">Test de Devianza</a></li>
<li><a href="#pseudo-r2-de-mcfadden">Pseudo-R2 de McFadden</a></li>
<li><a href="#presentación-de-resultados-1">Presentación de resultados</a></li>
<li><a href="#referencias">Referencias</a></li>
</ul></li>
<li><a href="#reporte-de-progreso">Reporte de progreso</a></li>
<li><a href="#foro-práctica-10">Foro práctica 10</a></li>
</ul>
</div>

<script>
  addClassKlippyTo("pre.r, pre.markdown");
  addKlippy('right', 'bottom', 'auto', '1', 'Copy code', 'Copied!');
</script>
<div id="objetivo" class="section level1">
<h1>Objetivo</h1>
<p>La siguiente práctica tiene el objetivo de introducir a los estudiantes en los <strong>modelos de regresión logística multivariada</strong>. Al igual que en la práctica anterior emplearemos una variable dependiente <em>dicotómica</em>, de modo tal que veremos de qué una serie de variables independientes nos permiten predecir la ocurrencia de un determinado evento. Para ello, utilizaremos la base de datos de la <a href="https://doi.org/10.7910/DVN/SRPWFW"><em>Encuesta sobre Conflicto y Cohesion Social en Chile 2014</em></a> para analizar los determinantes de la participación en las elecciones del año 2013.</p>
</div>
<div id="librerías" class="section level1">
<h1>Librerías</h1>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1">pacman<span class="op">::</span><span class="kw">p_load</span>(dplyr, summarytools, ggmosaic, sjPlot, texreg)</a></code></pre></div>
</div>
<div id="datos" class="section level1">
<h1>Datos</h1>
<p>La Encuesta sobre Conflicto y Cohesión Social en Chile (ENACOES 2014) es el primer estudio de este tipo que busca mapear los conflictos y la cohesión en el país. Su objetivo fundamental es aportar a la comprensión de las creencias, actitudes y percepciones de los chilenos hacia las distintas dimensiones de la convivencia y el conflicto. La población objetivo son hombre y mujeres entre 15 y 75 años de edad con un alcance nacional, donde se obtuvo una muestra final de <strong>2025</strong> casos. Para el caso de este ejercicio, se trabajara con una submuestra de <strong>1974</strong> individuos que estuvieron habilitados para votar en el año 2013.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" title="1"><span class="co">#Cargamos la base de datos desde internet</span></a>
<a class="sourceLine" id="cb2-2" title="2"><span class="kw">load</span>(<span class="kw">url</span>(<span class="st">&quot;https://multivariada.netlify.com/assignment/data/enacoes.RData&quot;</span>))</a></code></pre></div>
<div id="explorar-datos" class="section level2">
<h2>Explorar datos</h2>
<p>A partir de la siguiente tabla se obtienen estadísticos descriptivos que luego serán relevantes para la interpretación de nuestros modelos.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1"><span class="kw">view</span>(<span class="kw">dfSummary</span>(enacoes, <span class="dt">headings =</span> <span class="ot">FALSE</span>, <span class="dt">method =</span> <span class="st">&quot;render&quot;</span>))</a></code></pre></div>
<div class="container st-container">
<table class="table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline ">
  <thead>
    <tr>
      <th align="center" class="st-protect-top-border"><strong>No</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Variable</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Label</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Stats / Values</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Freqs (% of Valid)</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Graph</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Valid</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Missing</strong></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td align="center">1</td>
      <td align="left">voto
[factor]</td>
      <td align="left">Vot&#0243; en &#0250;ltima elecci&#0243;n</td>
      <td align="left">1. 0
2. 1</td>
      <td align="left" style="padding:0;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">649</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">32.9%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">1325</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">67.1%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr></table></td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHEAAAA4CAQAAABgIN//AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfkCAsCOCcXYeIKAAAAoElEQVRo3u3YMQ5AQBBAUSsuqOOEdI5IO6vSmE3+/NeJgp/Mkky7J7p59AuYaOIXS7w4Eg7m1jKy4kOW/tb686OvjL6XAoNqIoGJBCYSmEhgIoGJBCYSmEhgIsFrdzNit/K3FpdunM143MAVGFQTCbrPzYk5jHs4jMnb8Bz9f6HAoJpIYCKBiQQmEphIYCKBiQQmEphIUG0bzlRgUE0keABiEAvWoR6tDwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMC0wOC0xMVQwMjo1NjozOSswMDowMCvxCtsAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjAtMDgtMTFUMDI6NTY6MzkrMDA6MDBarLJnAAAAAElFTkSuQmCC"></td>
      <td align="center">1974
(100%)</td>
      <td align="center">0
(0%)</td>
    </tr>
    <tr>
      <td align="center">2</td>
      <td align="left">sexo
[factor]</td>
      <td align="left">Sexo entrevistado</td>
      <td align="left">1. 0
2. 1</td>
      <td align="left" style="padding:0;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">803</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">40.7%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">1171</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">59.3%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr></table></td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGUAAAA4CAQAAABOZf5tAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfkCAsCOCcXYeIKAAAAoElEQVRo3u3YMQqAMBAAQSN+0E5fqJ1P1PZiGQLZHDudSMSFRPDKu2Sxjn4BU3KnbPHiGnhwjtKyKi7a6lv7oJCnwzMSbTBTiEwhMoXIFCJTiEwhMoXIFCJTiH7/9j3+sUcpccgy36QyTlwSbTBTiKpjf093WM5wWCDTyTb19zbRBjOFyBQiU4hMITKFyBQiU4hMITKFKOt0cm6JNpgpRB/L3QvWo7bMFwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMC0wOC0xMVQwMjo1NjozOSswMDowMCvxCtsAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjAtMDgtMTFUMDI6NTY6MzkrMDA6MDBarLJnAAAAAElFTkSuQmCC"></td>
      <td align="center">1974
(100%)</td>
      <td align="center">0
(0%)</td>
    </tr>
    <tr>
      <td align="center">3</td>
      <td align="left">edad
[numeric]</td>
      <td align="left">Edad entrevistado</td>
      <td align="left">Mean (sd) : 45.1 (16)
min < med < max:
18 < 45 < 75
IQR (CV) : 26 (0.4)</td>
      <td align="left" style="vertical-align:middle">58 distinct values</td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuCAQAAABxABKuAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfkCAsCOCcXYeIKAAABpElEQVR42u3cXU7CQBhAUTEszwXoCmUB7k9fq2kTLvTfc970AZsbvpkpApfvF4rXrS/gaASLBIuuwx/2s57dJi/l/bL+1Qz/5PXhR1nY2+hvv7a+LCNZCRYJFu12DWumNon5t4iTBBvfJJbYIoxkJFgkWCRYJFj0xC65r/u9tTx1rNjr/d6SjGQkWLTaSf8sK94iwcbjnGPFWyTYWvd1W7CGRXc9w26Lvti/7KPP7c6RXHLIjjXARjISLDrcK65br3iHC7b1ac5IRoJFgkWCRYJFgkWCRYc7hzXzv+fi5MHmP+YayUiwSLBIsEiwSLBIsEiw6OQH1ynjdwD3nP//abDH/7VnJKN/+gwbN3Wr/jEYVcEG7rlVN5KRYJFgkWDRr0V/6/ctHMGfXXLrdy7sn5GMBIsEiwSLBIsEiwSLBIsEiwSLBIsEiwSLBIsEiwSLBIsEiwSLBIsEiwSLBIsEiwSLBIsEiwSLBIsEiwSLBIsEiwSLBIsEiwSLBIsEiwSLBIsEiwSLBIsEiwSLBIsuw8+UfvqA6ajh1zBcNGqMZCRYJFj0A41dKUVi6zkxAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIwLTA4LTExVDAyOjU2OjM5KzAwOjAwK/EK2wAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMC0wOC0xMVQwMjo1NjozOSswMDowMFqssmcAAAAASUVORK5CYII="></td>
      <td align="center">1974
(100%)</td>
      <td align="center">0
(0%)</td>
    </tr>
    <tr>
      <td align="center">4</td>
      <td align="left">educ
[factor]</td>
      <td align="left">Nivel Educacional</td>
      <td align="left">1. 1
2. 2
3. 3
4. 4
5. 5</td>
      <td align="left" style="padding:0;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">179</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">9.1%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">167</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">8.5%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">878</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">44.5%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">513</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">26.0%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">237</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">12.0%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr></table></td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAE8AAACACAQAAADgg/xsAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfkCAsCOCcXYeIKAAABA0lEQVR42u3awQqCQAAE0Ax/sFt9Yd36xLquwYqbuU745mRE9GBccKjhdUrOeW8A3nYZyxf3mRvxOvQilV80Tt+6VD7y7GX7SHi5eHh4eHhRwcPDwzsa7+Nhfq+H9lqGcv1kTPJyCoWXG86b3HuParv9Vu4Mr7Zz9zsw4eXi4eHh4UUFDw8PDy8qZngzqbgOLzect3CG98ytaHfhz839Mj2c4eXi4eHh4UUFDw8PDy8qZngzqbgOLzect+kMX/8b+oYz/BfHLLxcPDw8PLyo4OHh4eFFxQxvJhXX4eWG876Y4T3/oN48w/senvBy8fDw8PCigoeHh3c03j/t3LyEl4u3Jm+rbx1/G+R4GwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMC0wOC0xMVQwMjo1NjozOSswMDowMCvxCtsAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjAtMDgtMTFUMDI6NTY6MzkrMDA6MDBarLJnAAAAAElFTkSuQmCC"></td>
      <td align="center">1974
(100%)</td>
      <td align="center">0
(0%)</td>
    </tr>
  </tbody>
</table>
<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 0.9.6 (<a href='https://www.r-project.org/'>R</a> version 4.0.0)<br/>2020-08-10</p>
</div>
<p>Lo primero que debemos observar es la distribución de la participación electoral, donde 0 son quienes nos votaron en la última elección y 1 los que sí lo hicieron. En este caso, vemos que un 67,1% (1325) señaló haber participado en la última elección, en contraste de un 32,9% que no lo hizo. En este sentido, vemos que existen aproximadamente 2/3 de los individuos de la muestra que sí acudieron a votar, por tanto ahora vamos a revisar cómo se distribuyen estas respuestas según el sexo y el nivel educacional de el entrevistado.</p>
<p>En primera instancia nos centraremos en las variables <code>sexo</code> y <code>voto</code>. Como podemos notar la categoría de respuesta de estas variables son 0 y 1, es decir, estamos ante variables dicotómicas.</p>
<p>En segunda instancia, observaremos la distribución de participación electoral según el Nivel educacional (<code>educ</code>), la cual en este caso hemos recodificado en cinco niveles educacionales.</p>
<p>Con la función <code>tab_xtab</code> del paquete <code>sjPlot</code> podemos realizar una tabla de contingencia donde se señala la proporción de la participación electoral según sexo.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" title="1"><span class="kw">tab_xtab</span>(<span class="dt">var.row =</span> enacoes<span class="op">$</span>voto,enacoes<span class="op">$</span>sexo,<span class="dt">show.cell.prc =</span> T,<span class="dt">show.summary =</span> F)</a></code></pre></div>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
Votó en última<br>elección
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
Sexo entrevistado
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Hombre
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Mujer
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No votó
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">254</span><br><span style="color:#993333;">12.9 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">395</span><br><span style="color:#993333;">20 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">649</span><br><span style="color:#993333;">32.9 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Votó
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">549</span><br><span style="color:#993333;">27.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">776</span><br><span style="color:#993333;">39.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">1325</span><br><span style="color:#993333;">67.1 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">803</span><br><span style="color:#993333;">40.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1171</span><br><span style="color:#993333;">59.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1974</span><br><span style="color:#993333;">100 %</span>
</td>
</tr>
</table>
<p>Teniendo en cuenta que existen 2/3 (67,1%) de las personas en Chile que han declarado haber votado en la última elección, la tabla anterior nos muestra que del total de personas que votan, las participación electoral es mayor en las mujeres, lo cual equivale a un 39,3% del total en desmedro del 27,8% que representado por los hombres.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1"><span class="kw">tab_xtab</span>(<span class="dt">var.row =</span> enacoes<span class="op">$</span>voto,enacoes<span class="op">$</span>educ,</a>
<a class="sourceLine" id="cb5-2" title="2">         <span class="dt">show.cell.prc =</span> T,<span class="dt">show.summary =</span> F, <span class="dt">encoding =</span> <span class="st">&quot; &quot;</span>)</a></code></pre></div>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
Votó en última<br>elección
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="5">
Nivel Educacional
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Primaria incompleta<br>o menos
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Primaria
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Secundaria
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Técnica Superior
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Universitaria o<br>postgrado
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No votó
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">55</span><br><span style="color:#993333;">2.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">47</span><br><span style="color:#993333;">2.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">320</span><br><span style="color:#993333;">16.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">182</span><br><span style="color:#993333;">9.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">45</span><br><span style="color:#993333;">2.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">649</span><br><span style="color:#993333;">32.9 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Votó
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">124</span><br><span style="color:#993333;">6.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">120</span><br><span style="color:#993333;">6.1 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">558</span><br><span style="color:#993333;">28.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">331</span><br><span style="color:#993333;">16.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">192</span><br><span style="color:#993333;">9.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">1325</span><br><span style="color:#993333;">67.2 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">179</span><br><span style="color:#993333;">9.1 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">167</span><br><span style="color:#993333;">8.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">878</span><br><span style="color:#993333;">44.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">513</span><br><span style="color:#993333;">26 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">237</span><br><span style="color:#993333;">12 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1974</span><br><span style="color:#993333;">100 %</span>
</td>
</tr>
</table>
<p>Adicionalmente, la tabla anterior nos muestra la distribución de la participación electoral según cinco categorías de nivel educacional. Como podemos observar, la participación electoral se concentra en los niveles educacionales secundario con un 28,3% y superior técnica y universitaria, con un 16,8% y 9,7% respectivamente. Por otro lado, podemos observar una baja participación electoral de los grupos con nivel educacional más bajo, donde las personas con Primaria incompleta o menos representan un 6,3% y aquellas con Primaria completa son el 6,1%.</p>
<p>Al igual que la práctica anterior, podemos representar gráficamente estas distribuciones a través del paquete <code>ggmosaic</code> que con su función <code>geom_mosaic</code>. A continuación se presentan dos gráficos para la participación electoral según sexo y nivel educacional.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" title="1"><span class="kw">ggplot</span>(enacoes) <span class="op">+</span></a>
<a class="sourceLine" id="cb6-2" title="2"><span class="st">  </span><span class="kw">geom_mosaic</span>(<span class="kw">aes</span>(<span class="dt">x=</span><span class="kw">product</span>(voto, sexo), <span class="dt">fill=</span>sexo)) <span class="op">+</span></a>
<a class="sourceLine" id="cb6-3" title="3"><span class="st">  </span><span class="kw">geom_label</span>(<span class="dt">data =</span> <span class="kw">layer_data</span>(<span class="kw">last_plot</span>(), <span class="dv">1</span>),</a>
<a class="sourceLine" id="cb6-4" title="4">             <span class="kw">aes</span>(<span class="dt">x =</span> (xmin <span class="op">+</span><span class="st"> </span>xmax)<span class="op">/</span><span class="st"> </span><span class="dv">2</span>,</a>
<a class="sourceLine" id="cb6-5" title="5">                 <span class="dt">y =</span> (ymin <span class="op">+</span><span class="st"> </span>ymax)<span class="op">/</span><span class="st"> </span><span class="dv">2</span>,</a>
<a class="sourceLine" id="cb6-6" title="6">                 <span class="dt">label =</span> <span class="kw">paste0</span>(<span class="kw">round</span>((.wt<span class="op">/</span><span class="kw">sum</span>(.wt))<span class="op">*</span><span class="dv">100</span>,<span class="dv">1</span>),<span class="st">&quot;%&quot;</span>))) <span class="op">+</span></a>
<a class="sourceLine" id="cb6-7" title="7"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="st">&quot;Voto última elección&quot;,</span></a>
<a class="sourceLine" id="cb6-8" title="8"><span class="st">       x = &quot;</span>Sexo<span class="st">&quot;) +</span></a>
<a class="sourceLine" id="cb6-9" title="9"><span class="st">  scale_fill_discrete(name = &quot;&quot;,</span></a>
<a class="sourceLine" id="cb6-10" title="10"><span class="st">                      labels = c(&quot;</span>Hombre<span class="st">&quot;,&quot;</span>Mujer<span class="st">&quot;))+</span></a>
<a class="sourceLine" id="cb6-11" title="11"><span class="st">  scale_y_continuous(breaks = c(0,1),</span></a>
<a class="sourceLine" id="cb6-12" title="12"><span class="st">                   labels = c(&quot;</span>No votó&quot;,<span class="st">&quot;Votó&quot;)) +</span></a>
<a class="sourceLine" id="cb6-13" title="13"><span class="st">  theme(legend.position=&quot;</span>bottom<span class="st">&quot;)</span></a>
<a class="sourceLine" id="cb6-14" title="14"></a>
<a class="sourceLine" id="cb6-15" title="15"></a>
<a class="sourceLine" id="cb6-16" title="16"><span class="st">ggplot(enacoes) +</span></a>
<a class="sourceLine" id="cb6-17" title="17"><span class="st">  geom_mosaic(aes(x=product(voto, educ), fill=educ)) +</span></a>
<a class="sourceLine" id="cb6-18" title="18"><span class="st">  geom_label(data = layer_data(last_plot(), 1),</span></a>
<a class="sourceLine" id="cb6-19" title="19"><span class="st">             aes(x = (xmin + xmax)/2,</span></a>
<a class="sourceLine" id="cb6-20" title="20"><span class="st">                 y = (ymin + ymax)/2,</span></a>
<a class="sourceLine" id="cb6-21" title="21"><span class="st">                 label = paste0(round((.wt/sum(.wt))*100,1),&quot;</span>%<span class="st">&quot;))) +</span></a>
<a class="sourceLine" id="cb6-22" title="22"><span class="st">  labs(y = &quot;</span>Voto última elección&quot;,</a>
<a class="sourceLine" id="cb6-23" title="23">       <span class="dt">x =</span> <span class="st">&quot;Nivel Educacional&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb6-24" title="24"><span class="st">  </span><span class="kw">scale_fill_discrete</span>(<span class="dt">name =</span> <span class="st">&quot;&quot;</span>,</a>
<a class="sourceLine" id="cb6-25" title="25">                      <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Primaria incompleta o menos&quot;</span>,</a>
<a class="sourceLine" id="cb6-26" title="26">                                 <span class="st">&quot;Primaria&quot;</span>,</a>
<a class="sourceLine" id="cb6-27" title="27">                                 <span class="st">&quot;Secundaria&quot;</span>, <span class="st">&quot;Técnica o Superior&quot;</span>,</a>
<a class="sourceLine" id="cb6-28" title="28">                                 <span class="st">&quot;Universitaria o postgrado&quot;</span>))<span class="op">+</span></a>
<a class="sourceLine" id="cb6-29" title="29"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),<span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;No votó&quot;,&quot;</span>Votó&quot;)) <span class="op">+</span></a>
<a class="sourceLine" id="cb6-30" title="30"><span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position=</span><span class="st">&quot;bottom&quot;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-9"></span>
<img src="/assignment/10-code_files/figure-html/unnamed-chunk-9-1.png" alt="Participación electoral en 2013 según Sexo y Nivel Educacional" width="75%" /><img src="/assignment/10-code_files/figure-html/unnamed-chunk-9-2.png" alt="Participación electoral en 2013 según Sexo y Nivel Educacional" width="75%" />
<p class="caption">
Figure 1: Participación electoral en 2013 según Sexo y Nivel Educacional
</p>
</div>
</div>
</div>
<div id="estimación" class="section level1">
<h1>Estimación</h1>
<p>La función pincipal para la estimación de modelos de regresión logística es <code>glm()</code>, especificando el argumento <code>family="binomial"</code>, lo cual le indica a la función que estamos prediciendo una variable binaria. Al igual que con <code>lm()</code>, debemos especificar los predictores y la base de datos a emplear. A continuación, estimaremos una serie de modelos de regresión logística que nos permitan determinar de qué manera el sexo, la edad y el nivel educacional de las personas pueden predecir la participación electoral.</p>
<!-- > Aqui ecuacion del logit(p) =  -->
<!-- $ $ -->
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1">m00 &lt;-<span class="st"> </span><span class="kw">glm</span>(voto<span class="op">~</span><span class="dv">1</span>,<span class="dt">data =</span> enacoes,<span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)</a>
<a class="sourceLine" id="cb7-2" title="2">m01 &lt;-<span class="st"> </span><span class="kw">glm</span>(voto<span class="op">~</span>sexo,<span class="dt">data =</span> enacoes,<span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)</a>
<a class="sourceLine" id="cb7-3" title="3">m02 &lt;-<span class="st"> </span><span class="kw">glm</span>(voto<span class="op">~</span>edad,<span class="dt">data =</span> enacoes,<span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)</a>
<a class="sourceLine" id="cb7-4" title="4">m03 &lt;-<span class="st"> </span><span class="kw">glm</span>(voto<span class="op">~</span>sexo<span class="op">+</span>edad<span class="op">+</span>educ,<span class="dt">data =</span> enacoes,<span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)</a></code></pre></div>
<div id="presentación-de-resultados" class="section level2">
<h2>Presentación de resultados</h2>
<div class="alert alert-info">
<p>Para construir una tabla de regresión podemos usar la librería <code>texreg</code>:</p>
<p>Esto se puede hacer si se utiliza RMarkdown (no es requisito en este curso, para los interesad_s pueden revisar material del curso <a href="https://cienciasocialabierta.netlify.app/class/04-class/">ciencia social abierta</a> )</p>
<ol style="list-style-type: decimal">
<li><p>Instalar librería <strong>texreg</strong>. Si bien existe una versión en CRAN, no nos permite usar el argumento <code>custom.gof.rows</code> para agregar estadísticos de ajuste adicionales, así que para instalar:<code>remotes::install_github("leifeld/texreg")</code></p></li>
<li><p>Existen tres variaciones para crear tablas:</p>
<ul>
<li><code>screenreg()</code>: nos muestra la tabla en la consola de R</li>
<li><code>htmlreg()</code>: produce una tabla en formato html (como las que vemos en este documento)</li>
<li><code>texreg()</code>: produce una tabla en formato <span class="math inline">\(\LaTeX\)</span> para documentos en pdf.</li>
</ul></li>
<li><p>Para que el resultado pueda ser <code>renderizado</code> desde un documento RMarkdown a pdf o html, debe estar en un chunk con las siguientes especificaciones:</p></li>
</ol>
<pre><code>```{r results=&#39;asis&#39;, echo=FALSE}
htmlreg(list(m01,m02,m03))
```</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>Para personalizar nuestra tabla podemos ir agregando más información, tales como los nombres de los coeficientes o el nombre de los modelos:</li>
</ol>
<pre><code>```{r results=&#39;asis&#39;, echo=FALSE}
htmlreg(l = list(m00,m01,m02,m03),
        custom.coef.names=c(&quot;Intercepto&quot;,&quot;Sexo (Mujer=1)&quot;,&quot;Edad&quot;,&quot;Primaria&quot;,&quot;Secundaria&quot;, &quot;Técnica o Superior&quot;,&quot;Universitaria o postgrado&quot;),
        custom.model.names = c(&quot;Modelo 0&quot;,&quot;Modelo 1&quot;,&quot;Modelo 2&quot;, &quot;Modelo 3&quot;))
```</code></pre>
</div>
</div>
<div id="tabla-de-regresión" class="section level2">
<h2>Tabla de regresión</h2>
<table cellspacing="0" align="center" style="border: none;">
<tr>
<th style="text-align: left; border-top: 2px solid black; border-bottom: 1px solid black; padding-right: 12px;">
<b></b>
</th>
<th style="text-align: left; border-top: 2px solid black; border-bottom: 1px solid black; padding-right: 12px;">
<b>Modelo 0</b>
</th>
<th style="text-align: left; border-top: 2px solid black; border-bottom: 1px solid black; padding-right: 12px;">
<b>Modelo 1</b>
</th>
<th style="text-align: left; border-top: 2px solid black; border-bottom: 1px solid black; padding-right: 12px;">
<b>Modelo 2</b>
</th>
<th style="text-align: left; border-top: 2px solid black; border-bottom: 1px solid black; padding-right: 12px;">
<b>Modelo 3</b>
</th>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Intercepto
</td>
<td style="padding-right: 12px; border: none;">
0.71<sup style="vertical-align: 0px;">***</sup>
</td>
<td style="padding-right: 12px; border: none;">
0.77<sup style="vertical-align: 0px;">***</sup>
</td>
<td style="padding-right: 12px; border: none;">
-1.07<sup style="vertical-align: 0px;">***</sup>
</td>
<td style="padding-right: 12px; border: none;">
-2.04<sup style="vertical-align: 0px;">***</sup>
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
(0.05)
</td>
<td style="padding-right: 12px; border: none;">
(0.08)
</td>
<td style="padding-right: 12px; border: none;">
(0.15)
</td>
<td style="padding-right: 12px; border: none;">
(0.29)
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Sexo (Mujer=1)
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
-0.10
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
-0.02
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
(0.10)
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
(0.10)
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Edad
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
0.04<sup style="vertical-align: 0px;">***</sup>
</td>
<td style="padding-right: 12px; border: none;">
0.05<sup style="vertical-align: 0px;">***</sup>
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
(0.00)
</td>
<td style="padding-right: 12px; border: none;">
(0.00)
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Primaria
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
0.34
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
(0.25)
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Secundaria
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
0.47<sup style="vertical-align: 0px;">*</sup>
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
(0.19)
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Técnica o Superior
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
0.88<sup style="vertical-align: 0px;">***</sup>
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
(0.22)
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Universitaria o postgrado
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
1.53<sup style="vertical-align: 0px;">***</sup>
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
(0.25)
</td>
</tr>
<tr>
<td style="border-top: 1px solid black;">
AIC
</td>
<td style="border-top: 1px solid black;">
2502.30
</td>
<td style="border-top: 1px solid black;">
2503.34
</td>
<td style="border-top: 1px solid black;">
2334.32
</td>
<td style="border-top: 1px solid black;">
2290.54
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Log Likelihood
</td>
<td style="padding-right: 12px; border: none;">
-1250.15
</td>
<td style="padding-right: 12px; border: none;">
-1249.67
</td>
<td style="padding-right: 12px; border: none;">
-1165.16
</td>
<td style="padding-right: 12px; border: none;">
-1138.27
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Deviance
</td>
<td style="padding-right: 12px; border: none;">
2500.30
</td>
<td style="padding-right: 12px; border: none;">
2499.34
</td>
<td style="padding-right: 12px; border: none;">
2330.32
</td>
<td style="padding-right: 12px; border: none;">
2276.54
</td>
</tr>
<tr>
<td style="border-bottom: 2px solid black;">
Num. obs.
</td>
<td style="border-bottom: 2px solid black;">
1974
</td>
<td style="border-bottom: 2px solid black;">
1974
</td>
<td style="border-bottom: 2px solid black;">
1974
</td>
<td style="border-bottom: 2px solid black;">
1974
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;" colspan="6">
<span style="font-size:0.8em"><span class="math inline">\(^{***}\)</span> p &lt; 0.001; <span class="math inline">\(^{**}\)</span> p &lt; 0.01; <span class="math inline">\(^{*}\)</span> p &lt; 0.05 <br> Errores estándar entre paréntesis</span>
</td>
</tr>
</table>
<p>En la tabla anterior podemos observar cuatro modelos distintos:</p>
<table>
<thead>
<tr class="header">
<th align="right">Modelo</th>
<th align="right">Predictores</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">Modelo 0</td>
<td align="right">modelo nulo (sin predictores)</td>
</tr>
<tr class="even">
<td align="right">Modelo 1</td>
<td align="right">Incluye sexo</td>
</tr>
<tr class="odd">
<td align="right">Modelo 2</td>
<td align="right">Incluye edad</td>
</tr>
<tr class="even">
<td align="right">Modelo 3</td>
<td align="right">Incluye sexo, edad y nivel educacional</td>
</tr>
</tbody>
</table>
<div id="regresión-logística-sin-predictores" class="section level3">
<h3>Regresión logística sin predictores</h3>
<p><span class="math display">\[logit(p) = \beta_{0}\]</span></p>
<p>El modelo sin predictores nos permite conocer la probabilidad de votar. En este caso, vemos que se obtiene un intercepto de 0.71 correspondiente a <span class="math inline">\(log(p/1-p)\)</span>. En este caso <span class="math inline">\(p\)</span> es la probabilidad de que una persona participe en las elecciones como votante (voto = 1). Miremos nuevamente la distribución de la participación electoral:</p>
<table class="kable_wrapper">
<tbody>
<tr>
<td>
<table>
<thead>
<tr class="header">
<th align="right">val</th>
<th align="left">label</th>
<th align="right">frq</th>
<th align="right">raw.prc</th>
<th align="right">valid.prc</th>
<th align="right">cum.prc</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="left">No votó</td>
<td align="right">649</td>
<td align="right">32.88</td>
<td align="right">32.88</td>
<td align="right">32.88</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="left">Votó</td>
<td align="right">1325</td>
<td align="right">67.12</td>
<td align="right">67.12</td>
<td align="right">100.00</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
<p>Entonces, tenemos que <span class="math inline">\(p =1325/1974 = .67\)</span>. Por tanto, la odds calculadas corresponden a 0.67/(1-0.67) =2.03, lo cual en unidades de log(odds) corresponde al valore del intercepto que es 0.71. En otras palabras el intercepto del modelo sin predictores nos entrega la log-odds de votar en las elecciones. Adicionalmente, podemos transformar nuevamente a unidades de probabilidad de la siguiente manera: <code>p = exp(0.71)/(1 +  exp(0.71))= 0.67</code>.</p>
</div>
<div id="regresión-logistica-con-variable-binaria-como-predictor" class="section level3">
<h3>Regresión logistica con variable binaria como predictor</h3>
<p><span class="math display">\[logit(p) = \beta_0 + \beta_{mujer}\]</span></p>
<p>El modelo con un predictor binario como sexo nos permite estimar la probabilidad de votar para las mujeres (sexo = 1), respecto a los hombres (sexo = 0). En este caso, los resultados muestran el valor del intercepto (0.77) y para sexo (-0.10). Antes de interpretar, demos una mirada a la distribución de la participación electoral según sexo:</p>
<pre><code>##         sexo Hombre Mujer
## voto                     
## No votó         254   395
## Votó            549   776</code></pre>
<p>En nuestros datos, ¿cuáles son las chances (odds) de votar para los hombres y para las mujeres? Con la información de la tabla de contingencia podemos realizar los cálculos manualmente: para los hombres (sexo = 0), las odds de votar son (549/803)/(254/803) = 0.683 /0.316 = 2.16. A su vez, para las mujeres, las odds de votar son (776/1171)/(395/1171) = 0.662/0.337 = 1.96. Entonces, las odds ratio para las mujeres respecto de los hombres es (776/395)/(549/254) = (776x254)/(549x395) = 0.907, por lo tanto podemos decir que las odds de votar en las elecciones son son 9,5% (<code>exp(-0.10)-1 = 0.908-1</code>) más bajas para las mujeres respecto a los hombres.</p>
<p>Ahora, si observamos los resultados de la tabla de regresión vemos que el intercepto es 0.77, el cual representa las log-odds para los hombres en tanto corresponde a la categoría de referencia (sexo = 0). Usando las odds de votar para los hombres calculada en el apartado anterior, podemos confirmarlo: log(2.16) = 0.77. A su vez, el log-odds para las mujeres corresponde al log del odds-ratio de las odds de las mujeres y de los hombres calculado anteriormente: log(0.907) = -0.10. El output tradicional de R cuando usamos <code>glm()</code> nos entrega los coeficientes en unidades de log-odds, por tanto es necesario realizar la <strong>exponenciación</strong> de dichos coeficientes para realizar la interpretación en unidades de odds-ratio.</p>
</div>
<div id="regresión-logística-con-variable-continua-como-predictor" class="section level3">
<h3>Regresión logística con variable continua como predictor</h3>
<p><span class="math display">\[logit(p) = \beta_0 + \beta_{edad}\]</span></p>
<p>Ahora, estimaremos un modelo empleando la edad como predictor continuo. En este caso, el intercepto corresponde a los log-odds de una persona con “edad 0”. En otras palabras, las odds de votar cuando se tiene edad 0 es <code>exp(-1.07) = 0.343</code>. Lo importante es que si observamos la distribución de la variable edad, vemos que el valor mínimo es 18 años, por tanto, sabemos que este coeficiente no posee una interpretación sustantiva directamente. Lo más relevante es que el intercepto en ese modelo corresponde a los log-odds de votar en el <strong>hipotético caso</strong> de tener edad cero.</p>
<p>Entonces, ¿cómo interpretamos el coeficiente de edad?. Para esto, lo ideal es tener en cuenta todos los valores de la ecuación:</p>
<p><span class="math display">\[logit(p) =  -1.07 + 0.04 \times edad\]</span></p>
<p>Una manera de hacerlo es fijar edad en algún valor, por ejemplo un sujeto de con 54 años. Entonces, el valor del log-odds para una persona con 54 años es:</p>
<p><span class="math inline">\(logit(p_{edad54}) = -1.07 + 0.04 \times 54 = 1.09\)</span></p>
<p>Ahora, el valor de los log-odds para una persona con 55 años es:</p>
<p><span class="math inline">\(logit(p_{edad55}) = -1.07 + 0.04 \times 55 = 1.13\)</span></p>
<p>Entonces, podemos decir que el coeficiente para edad es la diferencia en el log-odds. En otras palabras, por una unidad de incremento en edad (1 año), el cambio esperado en los log-odds es de 0.04.</p>
<p>Ahora, ¿cómo traducimos este cambio en odds?. Tenemos que:</p>
<p><span class="math inline">\(\exp(logit(p_{edad55})-logit(p_{edad54}) = \frac{\exp(logit(p_{edad55}))}{\exp(logit(p_{edad55}))}= \frac{\exp(1.13)}{\exp(1.09)}=\frac{3.09}{2.97} = 1.04\)</span></p>
<p>Finalmente, podemos decir que por el incremento de una unidad en edad (1 año), se espera ver un incremento aproximado de un 4% en las odds de ir a votar. Este porcentaje no depende de los valores en los cuales se mantenga edad.</p>
</div>
<div id="regresión-logística-con-múltiples-predictores" class="section level3">
<h3>Regresión logística con múltiples predictores</h3>
<p><span class="math display">\[logit(p) = \beta_0 + \beta_{\text{mujer}}+ \beta_{\text{edad}}+ \beta_{\text{prim}}+ \beta_{\text{secu}}+ \beta_{\text{técn}}+ \beta_{\text{univ}}\]</span></p>
<p>Este ejemplo representa el modelo multivariado para participación electoral. Cada coeficiente prepresenta el cambio predicho en el log-odds de votar por un incremento/cambio en la variable, manteniendo todas las demás variables constantes. Cada coeficiente exponenciado (exp), representa el ratio de dos odds (por ejemplo, mujer respecto a hombre), o el cambio en las odds por el incremento de una unidad de la variable independiente (por ejemplo, un año de edad), <strong>manteniendo las demás variables constantes</strong>.</p>
<p>Entonces, si observamos el coeficiente de sexo en el Modelo 3, vemos que el odds-ratio de las mujeres sobre los hombres es de exp(-0.02)= 0.98, es decir que las odds de votar en las elecciones son son 1,9% (<code>exp(-0.02)-1 = 0.98-1</code>) más bajas para las mujeres respecto a los hombres, manteniendo edad y el nivel educacional constante.</p>
<p>La variable nivel educacional posee 5 niveles, donde “Primaria incompleta o menos” es la categoría de referencia, por tanto, los coeficientes se deben interpretar respecto dicha categoría. Por ejemplo, tenemos que el odds-ratio para Primaria es de exp(0.34) = 1.40, por lo tanto las odds de votar en las elecciones son 40% (<code>exp(-0.02)-1 = 1.40-1</code>) más altas para las personas que completaron la educación primaria respecto a quienes tienen educación primaria incompleta o menos, manteniendo sexo y edad en valores constantes.</p>
<p>Ahora, observando el log-odds para las personas son educación Universitaria o postgrado podemos calcular que el odds-ratio para esta categoría es de exp(1.53) = 4.61, lo cual nos indica que las odds de votar son 361% <code>exp(1.53)-1 = 4.61-1</code> más altas para las personas con educación universitaria o postgrado respecto a quienes tienen educación primaria incompleta o menos, manteniendo sexo y edad en valores constantes.</p>
<p>Otra alternativa de interpretación es a través del cálculo de las <strong>probabilidades predichas</strong>. Por ejemplo ¿cuál es la probabilidad de votar según los distintos niveles educacionales manteniendo constante sexo y edad?. En este caso usaremos una persona hipotética que es mujer (sexo=1) de 55 años.</p>
<p>Tenemos nuestros coeficientes para el Modelo 3:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1">m03<span class="op">$</span>coefficients</a></code></pre></div>
<pre><code>## (Intercept)       sexo1        edad       educ2       educ3       educ4 
## -2.03578412 -0.02351809  0.04911213  0.33653007  0.46911435  0.88442909 
##       educ5 
##  1.52605507</code></pre>
<p>Calculamos las log-odds para cada caso:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1">        <span class="co"># Intercept     sexo*1    edad*55    educ2       educ3      educ4      educ5</span></a>
<a class="sourceLine" id="cb13-2" title="2">ed01&lt;-<span class="st"> </span><span class="fl">-2.03578412</span><span class="op">+</span>(<span class="op">-</span><span class="fl">0.0235</span><span class="op">*</span><span class="dv">1</span>)<span class="op">+</span>(<span class="fl">0.0491</span><span class="op">*</span><span class="dv">55</span>)<span class="op">+</span>(<span class="fl">0.3365</span><span class="op">*</span><span class="dv">0</span>)<span class="op">+</span>(<span class="fl">0.4691</span><span class="op">*</span><span class="dv">0</span>)<span class="op">+</span>(<span class="fl">0.8844</span><span class="op">*</span><span class="dv">0</span>)<span class="op">+</span>(<span class="fl">1.5260</span><span class="op">*</span><span class="dv">0</span>) <span class="co"># mujer 55 anios Primaria incompleta</span></a>
<a class="sourceLine" id="cb13-3" title="3">ed02&lt;-<span class="st"> </span><span class="fl">-2.03578412</span><span class="op">+</span>(<span class="op">-</span><span class="fl">0.0235</span><span class="op">*</span><span class="dv">1</span>)<span class="op">+</span>(<span class="fl">0.0491</span><span class="op">*</span><span class="dv">55</span>)<span class="op">+</span>(<span class="fl">0.3365</span><span class="op">*</span><span class="dv">1</span>)<span class="op">+</span>(<span class="fl">0.4691</span><span class="op">*</span><span class="dv">0</span>)<span class="op">+</span>(<span class="fl">0.8844</span><span class="op">*</span><span class="dv">0</span>)<span class="op">+</span>(<span class="fl">1.5260</span><span class="op">*</span><span class="dv">0</span>) <span class="co"># mujer 55 anios Primaria</span></a>
<a class="sourceLine" id="cb13-4" title="4">ed03&lt;-<span class="st"> </span><span class="fl">-2.03578412</span><span class="op">+</span>(<span class="op">-</span><span class="fl">0.0235</span><span class="op">*</span><span class="dv">1</span>)<span class="op">+</span>(<span class="fl">0.0491</span><span class="op">*</span><span class="dv">55</span>)<span class="op">+</span>(<span class="fl">0.3365</span><span class="op">*</span><span class="dv">0</span>)<span class="op">+</span>(<span class="fl">0.4691</span><span class="op">*</span><span class="dv">1</span>)<span class="op">+</span>(<span class="fl">0.8844</span><span class="op">*</span><span class="dv">0</span>)<span class="op">+</span>(<span class="fl">1.5260</span><span class="op">*</span><span class="dv">0</span>) <span class="co"># mujer 55 anios Secundaria</span></a>
<a class="sourceLine" id="cb13-5" title="5">ed04&lt;-<span class="st"> </span><span class="fl">-2.03578412</span><span class="op">+</span>(<span class="op">-</span><span class="fl">0.0235</span><span class="op">*</span><span class="dv">1</span>)<span class="op">+</span>(<span class="fl">0.0491</span><span class="op">*</span><span class="dv">55</span>)<span class="op">+</span>(<span class="fl">0.3365</span><span class="op">*</span><span class="dv">0</span>)<span class="op">+</span>(<span class="fl">0.4691</span><span class="op">*</span><span class="dv">0</span>)<span class="op">+</span>(<span class="fl">0.8844</span><span class="op">*</span><span class="dv">1</span>)<span class="op">+</span>(<span class="fl">1.5260</span><span class="op">*</span><span class="dv">0</span>) <span class="co"># mujer 55 anios Tecnica</span></a>
<a class="sourceLine" id="cb13-6" title="6">ed05&lt;-<span class="st"> </span><span class="fl">-2.03578412</span><span class="op">+</span>(<span class="op">-</span><span class="fl">0.0235</span><span class="op">*</span><span class="dv">1</span>)<span class="op">+</span>(<span class="fl">0.0491</span><span class="op">*</span><span class="dv">55</span>)<span class="op">+</span>(<span class="fl">0.3365</span><span class="op">*</span><span class="dv">0</span>)<span class="op">+</span>(<span class="fl">0.4691</span><span class="op">*</span><span class="dv">0</span>)<span class="op">+</span>(<span class="fl">0.8844</span><span class="op">*</span><span class="dv">0</span>)<span class="op">+</span>(<span class="fl">1.5260</span><span class="op">*</span><span class="dv">1</span>) <span class="co"># mujer 55 anios Universitaria</span></a></code></pre></div>
<p>Calculamos las probabilidades predichas de la siguiente manera:</p>
<p><span class="math display">\[\text{Probabilidad}= \frac{\exp(\beta_0+\beta_jX_j)}{1+\exp(\beta_0+\beta_jX_j)} = \frac{\text{Odds}}{1+\text{Odds}}\]</span></p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" title="1">pr.ed01&lt;-<span class="st"> </span><span class="kw">exp</span>(ed01)<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span><span class="kw">exp</span>(ed01))</a>
<a class="sourceLine" id="cb14-2" title="2">pr.ed02&lt;-<span class="st"> </span><span class="kw">exp</span>(ed02)<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span><span class="kw">exp</span>(ed02))</a>
<a class="sourceLine" id="cb14-3" title="3">pr.ed03&lt;-<span class="st"> </span><span class="kw">exp</span>(ed03)<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span><span class="kw">exp</span>(ed03))</a>
<a class="sourceLine" id="cb14-4" title="4">pr.ed04&lt;-<span class="st"> </span><span class="kw">exp</span>(ed04)<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span><span class="kw">exp</span>(ed04))</a>
<a class="sourceLine" id="cb14-5" title="5">pr.ed05&lt;-<span class="st"> </span><span class="kw">exp</span>(ed05)<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span><span class="kw">exp</span>(ed05))</a></code></pre></div>
<p>Finalmente, se presenta la tabla resumen a continuación:</p>
<table>
<thead>
<tr class="header">
<th align="left">Nivel educacional</th>
<th align="right">log-odds</th>
<th align="right">exp(log-odds)</th>
<th align="right">exp(odds)/(1-exp(odds)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Primaria incompleta o menos</td>
<td align="right">0.641</td>
<td align="right">1.899</td>
<td align="right">0.655</td>
</tr>
<tr class="even">
<td align="left">Primaria</td>
<td align="right">0.978</td>
<td align="right">2.658</td>
<td align="right">0.727</td>
</tr>
<tr class="odd">
<td align="left">Secundaria</td>
<td align="right">1.110</td>
<td align="right">3.035</td>
<td align="right">0.752</td>
</tr>
<tr class="even">
<td align="left">Técnica</td>
<td align="right">1.526</td>
<td align="right">4.598</td>
<td align="right">0.821</td>
</tr>
<tr class="odd">
<td align="left">Univsersitaria</td>
<td align="right">2.167</td>
<td align="right">8.734</td>
<td align="right">0.897</td>
</tr>
</tbody>
</table>
<p>La librería <code>sjPlot</code> posee la función <code>plot_model()</code> la cual, dentro de otras cosas, nos permite visualizar las probabilidades predichas para un modelo de regresión logística.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1"><span class="kw">plot_model</span>(m03,<span class="dt">type =</span> <span class="st">&quot;pred&quot;</span>,</a>
<a class="sourceLine" id="cb15-2" title="2">           <span class="dt">terms =</span> <span class="st">&quot;educ&quot;</span>,</a>
<a class="sourceLine" id="cb15-3" title="3">           <span class="dt">title =</span> <span class="st">&quot;Probabilidades predichas para Voto según nivel educacional&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>()</a></code></pre></div>
<p><img src="/assignment/10-code_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>En conjunto, podemos observar que en la medida que aumenta el nivel educacional de las personas, la probabilidad de que participen en las elecciones tiende a ser mayor, manteniendo edad y sexo constante.</p>
</div>
</div>
</div>
<div id="medidas-de-ajuste" class="section level1">
<h1>Medidas de Ajuste</h1>
<p>El ajuste de los modelos de regresión logística puede ser evaluado de distintas maneras. Generalmente se realiza a través del contraste con otros modelos con más o menos predictores, lo cual nos permite elegir entre las mejores especificaciones. Adicionalmente, presentaremos la manera de incorporar estas medidas de ajuste a la tabla de regresión del apartado anterior.</p>
<p>En este ejercicio emplearemos (1) Test de Devianza y (2) Pseudo-R2 de McFadden.</p>
<div id="test-de-devianza" class="section level2">
<h2>Test de Devianza</h2>
<p>Este test nos permite comparar las verosimilitudes del modelo con predictores, respecto a un modelo con menos predictores. En este caso, emplearemos la función <code>anova()</code> el cual realiza un test basado en la distribución chi-cuadrado donde se contrasta el modelo en cuestión respecto a un modelo sin predictores (modelo “nulo”).</p>
<p>En nuestro caso, comparamos nuestro modelo sin predictores con los posteriores modelos para sexo, edad y nivel educacional.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" title="1">test01&lt;-<span class="st"> </span><span class="kw">anova</span>(m00,m01,<span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a>
<a class="sourceLine" id="cb16-2" title="2">test02&lt;-<span class="st"> </span><span class="kw">anova</span>(m00,m02,<span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a>
<a class="sourceLine" id="cb16-3" title="3">test03&lt;-<span class="st"> </span><span class="kw">anova</span>(m00,m03,<span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a>
<a class="sourceLine" id="cb16-4" title="4">lrt01&lt;-<span class="st"> </span><span class="kw">rbind</span>(test01,test02,test03) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">unique</span>()</a>
<a class="sourceLine" id="cb16-5" title="5"><span class="kw">row.names</span>(lrt01) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Modelo nulo&quot;</span>,</a>
<a class="sourceLine" id="cb16-6" title="6">                      <span class="st">&quot;Modelo 1&quot;</span>,</a>
<a class="sourceLine" id="cb16-7" title="7">                      <span class="st">&quot;Modelo 2&quot;</span>,</a>
<a class="sourceLine" id="cb16-8" title="8">                      <span class="st">&quot;Modelo 3&quot;</span>)</a>
<a class="sourceLine" id="cb16-9" title="9">knitr<span class="op">::</span><span class="kw">kable</span>(lrt01,<span class="dt">digits =</span> <span class="dv">3</span>, <span class="dt">caption =</span> <span class="st">&quot;Test de devianza entre modelos&quot;</span>)</a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-19">Table 1: </span>Test de devianza entre modelos</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">Resid. Df</th>
<th align="right">Resid. Dev</th>
<th align="right">Df</th>
<th align="right">Deviance</th>
<th align="right">Pr(&gt;Chi)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Modelo nulo</td>
<td align="right">1973</td>
<td align="right">2500.296</td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
</tr>
<tr class="even">
<td>Modelo 1</td>
<td align="right">1972</td>
<td align="right">2499.342</td>
<td align="right">1</td>
<td align="right">0.954</td>
<td align="right">0.329</td>
</tr>
<tr class="odd">
<td>Modelo 2</td>
<td align="right">1972</td>
<td align="right">2330.325</td>
<td align="right">1</td>
<td align="right">169.971</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td>Modelo 3</td>
<td align="right">1967</td>
<td align="right">2276.545</td>
<td align="right">6</td>
<td align="right">223.751</td>
<td align="right">0.000</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: decimal">
<li><p><strong>Modelo nulo vs. Modelo 1</strong>: La diferencia entre los modelos no es estadísticamente significativa con una probabilidad <span class="math inline">\(p\)</span> &gt; 0.05. Por lo tanto el modelo que incluye sexo como predictor <strong>no ofrece</strong> un mejor ajuste a los datos que un modelo sin predictores.</p></li>
<li><p><strong>Modelo nulo vs. Modelo 2</strong>: La diferencia entre los modelos es estadísticamente significativa con una probabilidad <span class="math inline">\(p\)</span> &lt; 0.001. Por lo tanto el modelo que incluye la edad como predictor <strong>ofrece</strong> un mejor ajuste a los datos que un modelo sin predictores.</p></li>
<li><p><strong>Modelo nulo vs. Modelo 3</strong>: La diferencia entre los modelos es estadísticamente significativa con una probabilidad <span class="math inline">\(p\)</span> &lt; 0.001. Por lo tanto el modelo que incluye el sexo, edad y nivel educacional como predictores <strong>ofrece</strong> un mejor ajuste a los datos que un modelo sin predictores.</p></li>
</ol>
<p><strong>Podemos guardar los valores <span class="math inline">\(p\)</span> de cada modelo para luego incorporarlos en la tabla de regresión:</strong></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" title="1">test.pvalues1&lt;-<span class="st"> </span>test01<span class="op">$</span><span class="st">`</span><span class="dt">Pr(&gt;Chi)</span><span class="st">`</span>[<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb17-2" title="2">test.pvalues2&lt;-<span class="st"> </span>test02<span class="op">$</span><span class="st">`</span><span class="dt">Pr(&gt;Chi)</span><span class="st">`</span>[<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb17-3" title="3">test.pvalues3&lt;-<span class="st"> </span>test03<span class="op">$</span><span class="st">`</span><span class="dt">Pr(&gt;Chi)</span><span class="st">`</span>[<span class="dv">2</span>]</a></code></pre></div>
</div>
<div id="pseudo-r2-de-mcfadden" class="section level2">
<h2>Pseudo-R2 de McFadden</h2>
<p>Esta medida de ajuste nos entrega una magnitud comparativa entre el modelo con predictores y el modelo nulo (sin predictores). Este se basda en los valores del loglikelihood de cada modelo.</p>
<p><span class="math inline">\(1-\frac{LL(LM)}{LL(L0)}\)</span></p>
<ul>
<li>LL es el log likelihood del modelo</li>
<li>LM es el modelo posterior (con predictores)</li>
<li>L0 es el modelo nulo</li>
</ul>
<p>Podemos calcularlos manualmente de la siguiente manera:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" title="1"><span class="dv">1</span><span class="op">-</span>(<span class="kw">logLik</span>(m01)[<span class="dv">1</span>]<span class="op">/</span><span class="st"> </span><span class="kw">logLik</span>(m00)[<span class="dv">1</span>]) <span class="co"># modelo 1 vs modelo nulo</span></a>
<a class="sourceLine" id="cb18-2" title="2"><span class="dv">1</span><span class="op">-</span>(<span class="kw">logLik</span>(m02)[<span class="dv">1</span>]<span class="op">/</span><span class="st"> </span><span class="kw">logLik</span>(m00)[<span class="dv">1</span>]) <span class="co"># modelo 2 vs modelo nulo</span></a>
<a class="sourceLine" id="cb18-3" title="3"><span class="dv">1</span><span class="op">-</span>(<span class="kw">logLik</span>(m03)[<span class="dv">1</span>]<span class="op">/</span><span class="st"> </span><span class="kw">logLik</span>(m00)[<span class="dv">1</span>]) <span class="co"># modelo 3 vs modelo nulo</span></a></code></pre></div>
<pre><code>## [1] 0.0003817169
## [1] 0.06798047
## [1] 0.08948998</code></pre>
<p>También, podemos utilizar la función <code>PseudoR2()</code> de la librería <code>DescTools</code>. <strong>A continuación los calculamos y guardamos para incluirlos en la tabla de regresión.</strong></p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" title="1">mfr2<span class="fl">.00</span> &lt;-<span class="st"> </span>DescTools<span class="op">::</span><span class="kw">PseudoR2</span>(m00)</a>
<a class="sourceLine" id="cb20-2" title="2">mfr2<span class="fl">.01</span> &lt;-<span class="st"> </span>DescTools<span class="op">::</span><span class="kw">PseudoR2</span>(m01)</a>
<a class="sourceLine" id="cb20-3" title="3">mfr2<span class="fl">.02</span> &lt;-<span class="st"> </span>DescTools<span class="op">::</span><span class="kw">PseudoR2</span>(m02)</a>
<a class="sourceLine" id="cb20-4" title="4">mfr2<span class="fl">.03</span> &lt;-<span class="st"> </span>DescTools<span class="op">::</span><span class="kw">PseudoR2</span>(m03)</a></code></pre></div>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" title="1">r2&lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">cbind</span>(<span class="kw">c</span>(mfr2<span class="fl">.00</span>,mfr2<span class="fl">.01</span>,mfr2<span class="fl">.02</span>,mfr2<span class="fl">.03</span>)))</a>
<a class="sourceLine" id="cb21-2" title="2"><span class="kw">rownames</span>(r2) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Modelo nulo&quot;</span>,</a>
<a class="sourceLine" id="cb21-3" title="3">                  <span class="st">&quot;Modelo 1&quot;</span>,</a>
<a class="sourceLine" id="cb21-4" title="4">                  <span class="st">&quot;Modelo 2&quot;</span>,</a>
<a class="sourceLine" id="cb21-5" title="5">                  <span class="st">&quot;Modelo 3&quot;</span>)</a>
<a class="sourceLine" id="cb21-6" title="6">knitr<span class="op">::</span><span class="kw">kable</span>(r2,<span class="dt">digits =</span> <span class="dv">3</span>, <span class="dt">col.names =</span> <span class="kw">c</span>(<span class="st">&quot;McFadden R2&quot;</span>))</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">Mc</th>
<th align="left">Fadden R2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">Modelo nulo</td>
<td align="left">0.000</td>
</tr>
<tr class="even">
<td align="right">Modelo 1</td>
<td align="left">0.000</td>
</tr>
<tr class="odd">
<td align="right">Modelo 2</td>
<td align="left">0.068</td>
</tr>
<tr class="even">
<td align="right">Modelo 3</td>
<td align="left">0.089</td>
</tr>
</tbody>
</table>
<p>De esta manera, podemos observar que el cálculo del Pseudo R2 nos indica que el Modelo 1 no aporta mayor a la predicción, en contraste con el Modelo 2 y 3.</p>
</div>
<div id="presentación-de-resultados-1" class="section level2">
<h2>Presentación de resultados</h2>
<p>Existen distintas librerías para presentar modelos de regresión, tales como las funciones <code>tab_modeñ()</code> o <code>stargazer()</code> que ya hemos revisado anteriormente. En este caso vamos a usar <code>htmlreg()</code> de la librería <code>texreg</code>. Por defecto, la función nos entrega la siguiente salida:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" title="1"><span class="kw">htmlreg</span>(<span class="dt">l =</span> <span class="kw">list</span>(m03,m03))</a></code></pre></div>
&lt;!DOCTYPE HTML PUBLIC “-//W3C//DTD HTML 4.01 Transitional//EN” “<a href="http://www.w3.org/TR/html4/loose.dtd" class="uri">http://www.w3.org/TR/html4/loose.dtd</a>”&gt;
<table cellspacing="0" align="center" style="border: none;">
<caption align="bottom" style="margin-top:0.3em;">
Statistical models
</caption>
<tr>
<th style="text-align: left; border-top: 2px solid black; border-bottom: 1px solid black; padding-right: 12px;">
<b></b>
</th>
<th style="text-align: left; border-top: 2px solid black; border-bottom: 1px solid black; padding-right: 12px;">
<b>Model 1</b>
</th>
<th style="text-align: left; border-top: 2px solid black; border-bottom: 1px solid black; padding-right: 12px;">
<b>Model 2</b>
</th>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
(Intercept)
</td>
<td style="padding-right: 12px; border: none;">
-2.04<sup style="vertical-align: 0px;">***</sup>
</td>
<td style="padding-right: 12px; border: none;">
-2.04<sup style="vertical-align: 0px;">***</sup>
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
(0.29)
</td>
<td style="padding-right: 12px; border: none;">
(0.29)
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
sexo1
</td>
<td style="padding-right: 12px; border: none;">
-0.02
</td>
<td style="padding-right: 12px; border: none;">
-0.02
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
(0.10)
</td>
<td style="padding-right: 12px; border: none;">
(0.10)
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
edad
</td>
<td style="padding-right: 12px; border: none;">
0.05<sup style="vertical-align: 0px;">***</sup>
</td>
<td style="padding-right: 12px; border: none;">
0.05<sup style="vertical-align: 0px;">***</sup>
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
(0.00)
</td>
<td style="padding-right: 12px; border: none;">
(0.00)
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
educ2
</td>
<td style="padding-right: 12px; border: none;">
0.34
</td>
<td style="padding-right: 12px; border: none;">
0.34
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
(0.25)
</td>
<td style="padding-right: 12px; border: none;">
(0.25)
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
educ3
</td>
<td style="padding-right: 12px; border: none;">
0.47<sup style="vertical-align: 0px;">*</sup>
</td>
<td style="padding-right: 12px; border: none;">
0.47<sup style="vertical-align: 0px;">*</sup>
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
(0.19)
</td>
<td style="padding-right: 12px; border: none;">
(0.19)
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
educ4
</td>
<td style="padding-right: 12px; border: none;">
0.88<sup style="vertical-align: 0px;">***</sup>
</td>
<td style="padding-right: 12px; border: none;">
0.88<sup style="vertical-align: 0px;">***</sup>
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
(0.22)
</td>
<td style="padding-right: 12px; border: none;">
(0.22)
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
educ5
</td>
<td style="padding-right: 12px; border: none;">
1.53<sup style="vertical-align: 0px;">***</sup>
</td>
<td style="padding-right: 12px; border: none;">
1.53<sup style="vertical-align: 0px;">***</sup>
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
(0.25)
</td>
<td style="padding-right: 12px; border: none;">
(0.25)
</td>
</tr>
<tr>
<td style="border-top: 1px solid black;">
AIC
</td>
<td style="border-top: 1px solid black;">
2290.54
</td>
<td style="border-top: 1px solid black;">
2290.54
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
BIC
</td>
<td style="padding-right: 12px; border: none;">
2329.66
</td>
<td style="padding-right: 12px; border: none;">
2329.66
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Log Likelihood
</td>
<td style="padding-right: 12px; border: none;">
-1138.27
</td>
<td style="padding-right: 12px; border: none;">
-1138.27
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Deviance
</td>
<td style="padding-right: 12px; border: none;">
2276.54
</td>
<td style="padding-right: 12px; border: none;">
2276.54
</td>
</tr>
<tr>
<td style="border-bottom: 2px solid black;">
Num. obs.
</td>
<td style="border-bottom: 2px solid black;">
1974
</td>
<td style="border-bottom: 2px solid black;">
1974
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;" colspan="4">
<span style="font-size:0.8em"><sup style="vertical-align: 0px;"><em><strong></sup>p &lt; 0.001, <sup style="vertical-align: 0px;"></strong></sup>p &lt; 0.01, <sup style="vertical-align: 0px;"></em></sup>p &lt; 0.05</span>
</td>
</tr>
</table>
<p>Dentro de la misma función, existen más opciones para personalizar el reporte, incluyendo el argumento <code>custom.gof.rows</code> señalado en el apartado anterior, el cual emplearemos para incluirlos resultados delTest de Devianza y el Pseudo R2. En este caso, incluiremos una versión con coeficientes en log-odds del Modelo 3 y su posterior transformación a odds-ratio (OR), además de remplazar los errores estándar por intervalos de confianza.</p>
<p><strong>Para transformar los coeficientes de log-odds a odds-ratio realizamos lo siguiente:</strong></p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" title="1">or &lt;-<span class="st"> </span>texreg<span class="op">::</span><span class="kw">extract</span>(m03)</a>
<a class="sourceLine" id="cb23-2" title="2">or<span class="op">@</span>coef &lt;-<span class="st"> </span><span class="kw">exp</span>(or<span class="op">@</span>coef)</a></code></pre></div>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" title="1"><span class="kw">htmlreg</span>(<span class="dt">l =</span> <span class="kw">list</span>(m03,or), <span class="dt">doctype =</span> F,<span class="dt">caption =</span> <span class="st">&quot;&quot;</span>,<span class="dt">caption.above =</span> T,</a>
<a class="sourceLine" id="cb24-2" title="2">        <span class="dt">custom.model.names =</span> <span class="kw">c</span>(<span class="st">&quot;Modelo 3&quot;</span>, <span class="st">&quot;Modelo 3 (OR)&quot;</span>),</a>
<a class="sourceLine" id="cb24-3" title="3">        <span class="dt">custom.coef.names =</span> coef.labs,</a>
<a class="sourceLine" id="cb24-4" title="4">        <span class="dt">ci.force =</span> <span class="kw">c</span>(<span class="ot">TRUE</span>,<span class="ot">TRUE</span>),</a>
<a class="sourceLine" id="cb24-5" title="5">        <span class="dt">override.coef =</span> <span class="kw">list</span>(<span class="kw">coef</span>(m03),or<span class="op">@</span>coef),</a>
<a class="sourceLine" id="cb24-6" title="6">        <span class="dt">custom.gof.rows=</span><span class="kw">list</span>(<span class="st">&quot;Deviance Test ($p$)&quot;</span> =<span class="st"> </span><span class="kw">c</span>(test.pvalues3,</a>
<a class="sourceLine" id="cb24-7" title="7">                                                       test.pvalues3),</a>
<a class="sourceLine" id="cb24-8" title="8">                             <span class="st">&quot;Pseudo R2&quot;</span> =<span class="st"> </span><span class="kw">c</span>(mfr2<span class="fl">.03</span>,mfr2<span class="fl">.03</span>)),</a>
<a class="sourceLine" id="cb24-9" title="9">          <span class="dt">custom.note =</span> <span class="st">&quot;$^{***}$ p &lt; 0.001; $^{**}$ p &lt; 0.01; $^{*}$ p &lt; 0.05 &lt;br&gt; Errores estándar entre paréntesis. &lt;br&gt; **Nota**: La significancia estadística de los coeficientes en unidades de Odds ratio está calculada en base a los valores $t$, &lt;br&gt; los cuales a su vez se calculan en base a $log(Odds)/SE$&quot;</span>)</a></code></pre></div>
<table cellspacing="0" align="center" style="border: none;">
<tr>
<th style="text-align: left; border-top: 2px solid black; border-bottom: 1px solid black; padding-right: 12px;">
<b></b>
</th>
<th style="text-align: left; border-top: 2px solid black; border-bottom: 1px solid black; padding-right: 12px;">
<b>Modelo 3</b>
</th>
<th style="text-align: left; border-top: 2px solid black; border-bottom: 1px solid black; padding-right: 12px;">
<b>Modelo 3 (OR)</b>
</th>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Intercepto
</td>
<td style="padding-right: 12px; border: none;">
-2.04<sup style="vertical-align: 0px;">*</sup>
</td>
<td style="padding-right: 12px; border: none;">
0.13
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
[-2.60; -1.47]
</td>
<td style="padding-right: 12px; border: none;">
[-0.43; 0.70]
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Sexo (Mujer=1)
</td>
<td style="padding-right: 12px; border: none;">
-0.02
</td>
<td style="padding-right: 12px; border: none;">
0.98<sup style="vertical-align: 0px;">*</sup>
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
[-0.23; 0.18]
</td>
<td style="padding-right: 12px; border: none;">
[0.77; 1.18]
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Edad
</td>
<td style="padding-right: 12px; border: none;">
0.05<sup style="vertical-align: 0px;">*</sup>
</td>
<td style="padding-right: 12px; border: none;">
1.05<sup style="vertical-align: 0px;">*</sup>
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
[0.04; 0.06]
</td>
<td style="padding-right: 12px; border: none;">
[1.04; 1.06]
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Primaria
</td>
<td style="padding-right: 12px; border: none;">
0.34
</td>
<td style="padding-right: 12px; border: none;">
1.40<sup style="vertical-align: 0px;">*</sup>
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
[-0.15; 0.82]
</td>
<td style="padding-right: 12px; border: none;">
[0.91; 1.89]
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Secundaria
</td>
<td style="padding-right: 12px; border: none;">
0.47<sup style="vertical-align: 0px;">*</sup>
</td>
<td style="padding-right: 12px; border: none;">
1.60<sup style="vertical-align: 0px;">*</sup>
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
[0.09; 0.85]
</td>
<td style="padding-right: 12px; border: none;">
[1.22; 1.98]
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Técnica o Superior
</td>
<td style="padding-right: 12px; border: none;">
0.88<sup style="vertical-align: 0px;">*</sup>
</td>
<td style="padding-right: 12px; border: none;">
2.42<sup style="vertical-align: 0px;">*</sup>
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
[0.46; 1.31]
</td>
<td style="padding-right: 12px; border: none;">
[2.00; 2.84]
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Universitaria o postgrado
</td>
<td style="padding-right: 12px; border: none;">
1.53<sup style="vertical-align: 0px;">*</sup>
</td>
<td style="padding-right: 12px; border: none;">
4.60<sup style="vertical-align: 0px;">*</sup>
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
</td>
<td style="padding-right: 12px; border: none;">
[1.03; 2.02]
</td>
<td style="padding-right: 12px; border: none;">
[4.11; 5.09]
</td>
</tr>
<tr>
<td style="border-top: 1px solid black;">
AIC
</td>
<td style="border-top: 1px solid black;">
2290.54
</td>
<td style="border-top: 1px solid black;">
2290.54
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
BIC
</td>
<td style="padding-right: 12px; border: none;">
2329.66
</td>
<td style="padding-right: 12px; border: none;">
2329.66
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Log Likelihood
</td>
<td style="padding-right: 12px; border: none;">
-1138.27
</td>
<td style="padding-right: 12px; border: none;">
-1138.27
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;">
Deviance
</td>
<td style="padding-right: 12px; border: none;">
2276.54
</td>
<td style="padding-right: 12px; border: none;">
2276.54
</td>
</tr>
<tr>
<td style="border-bottom: 2px solid black;">
Num. obs.
</td>
<td style="border-bottom: 2px solid black;">
1974
</td>
<td style="border-bottom: 2px solid black;">
1974
</td>
</tr>
<tr>
<td style="padding-right: 12px; border: none;" colspan="4">
<span style="font-size:0.8em"><span class="math inline">\(^{***}\)</span> p &lt; 0.001; <span class="math inline">\(^{**}\)</span> p &lt; 0.01; <span class="math inline">\(^{*}\)</span> p &lt; 0.05 <br> Errores estándar entre paréntesis. <br> <strong>Nota</strong>: La significancia estadística de los coeficientes en unidades de Odds ratio está calculada en base a los valores <span class="math inline">\(t\)</span>, <br> los cuales a su vez se calculan en base a <span class="math inline">\(log(Odds)/SE\)</span></span>
</td>
</tr>
</table>
<p>Una alternativa a las tablas de regresión son los <strong>coefplots</strong>. Como hemos visto en prácticas anteriores, este tipo de gráficos muestran el valor de coeficiente acompañados de sus intervalos de confianza. En este caso, vemos que la función <code>plot_model</code> nos entrega por defecto los coeficientes en unidades de odds-ratio, por tanto el valor 1 representa el límite para la significancia estadística, a diferencia del 0 cuando se encuentra en unidades de log-odds. En este caso, conforme a lo presentado en la tabla de regresión, el coeficiente de Edad y Educación Secundaria, Técnica superior y Universitaria poseen intervalos de confianza que no contienen el valor 1, por tanto son estadísticamente signficativos.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" title="1">plot02&lt;-<span class="st"> </span><span class="kw">plot_model</span>(m03,<span class="dt">vline.color =</span> <span class="st">&quot;grey&quot;</span>)</a>
<a class="sourceLine" id="cb25-2" title="2">plot01&lt;-<span class="st"> </span><span class="kw">plot_model</span>(m03,<span class="dt">vline.color =</span> <span class="st">&quot;grey&quot;</span>,<span class="dt">transform =</span> <span class="ot">NULL</span>)</a>
<a class="sourceLine" id="cb25-3" title="3"><span class="kw">plot_grid</span>(<span class="kw">list</span>(plot02,plot01),<span class="dt">tags =</span> <span class="kw">c</span>(<span class="st">&quot; &quot;</span>,<span class="st">&quot; &quot;</span>),</a>
<a class="sourceLine" id="cb25-4" title="4">          <span class="dt">margin =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>))</a></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-27"></span>
<img src="/assignment/10-code_files/figure-html/unnamed-chunk-27-1.png" alt="Modelo de regresión con y sin exponenciar (exp)" width="672" />
<p class="caption">
Figure 2: Modelo de regresión con y sin exponenciar (exp)
</p>
</div>
</div>
<div id="referencias" class="section level2">
<h2>Referencias</h2>
<p><a href="https://multivariada.netlify.app/docs/lecturas/Camarero_Odd_Ratio_LogitV2.pdf">Camarero et al (2017) Regresión logística: Fundamentos y aplicación a la investigación sociológica (p.30-52)</a></p>
<p><a href="https://scielo.conicyt.cl/scielo.php?script=sci_arttext&amp;pid=S0034-98872013001000014">Cerda, Vera y Rada (2017) Odds ratio: aspectos teóricos y prácticos.</a></p>
</div>
</div>
<div id="reporte-de-progreso" class="section level1">
<h1>Reporte de progreso</h1>
<p>Contestar <a href="https://forms.gle/q41sDrErFgTzKNbe6">aquí</a>.</p>
</div>
<div id="foro-práctica-10" class="section level1">
<h1>Foro práctica 10</h1>
</div>

                    </div>

                    



                    
                </div>

                <div class="body-footer">
                    <p>Last updated on August 10, 2020</p>

                    




                    
<section id="comments">
  
    
<div id="disqus_thread"></div>
<script>
  let disqus_config = function () {
    
    
    
  };
  (function() {
    if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
      document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
      return;
    }
    var d = document, s = d.createElement('script'); s.async = true;
    s.src = 'https://' + "multivariada-netlify-app" + '.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>


  
</section>


                </div>

            </article>

            <footer>
    <hr>

    <div class="row course-info">
        <div class="col-md-7">
            <p>
                <strong>SOC 01024: Estadística Multivariada (Primer semestre)</strong><br>

                <a href="https://www.uchile.cl/" target="_blank" rel="noopener">Universidad de Chile</a> &emsp;&emsp;
                <a href="http://www.facso.uchile.cl/sociologia" target="_blank" rel="noopener">Departamento de Sociología</a>
            </p>

            <p>
                <a href="https://jc-castillo.com" target="_blank" rel="noopener"><i class="fas fa-user"></i>
                    Juan Carlos Castillo</a> &emsp;&emsp;
                <a href="mailto:juancastillov@uchile.cl"><i class="fas fa-envelope"></i>
                    juancastillov@uchile.cl</a>
            </p>

            <p>
                <i class="far fa-calendar-alt"></i> Viernes &emsp;&emsp;
                <i class="far fa-clock"></i> 10:15am - 12:00pm <br>
                <i class="fas fa-university"></i> Online
            </p>
        </div>

        <div class="col-md-5 credits">
            <p>All content licensed under a <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.</p>
            
            <p>Content <i class="fab fa-creative-commons"></i> 2020 <a href="https://jc-castillo.com" target="_blank" rel="noopener">Juan Carlos Castillo</a></p>                    
            
            <p><a href="https://github.com/juancarloscastillo/multivariada" target="_blank" rel="noopener"><i class="fab fa-github"></i> View the source at GitHub.</a></p>
        </div>
    </div>
</footer>


        </main>
    </div>
</div>

        

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js" integrity="sha256-1zu+3BnLYV9LdiY85uXMzii3bdrkelyp37e0ZyTAQh0=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/r.min.js"></script>
        
      

    

    
    

    
    
    <script>const code_highlighting = true;</script>
    

    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.1.1/anchor.min.js" integrity="sha256-pB/deHc9CGfFpJRjC43imB29Rse8tak+5eXqntO94ck=" crossorigin="anonymous"></script>
    <script>
      anchors.add();
    </script>
    

    

    
    

    
    

    
    
    <script id="dsq-count-scr" src="https://multivariada-netlify-app.disqus.com/count.js" async></script>
    

    
    
    
    
    
    
    
    
    
    
    
    
    <script src="/js/academic.min.e5c8525332f417fe3589df9a6b25b6c4.js"></script>

    






    
    

    
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
