---
title: "Práctica 9. Regresión Logística 1"
subtitle: "Estadistica Multivariada - Sociología FACSO Universidad de Chile"
author: "Valentina Andrade"
linktitle: "Práctica 9. Regresión Logística 1"
date: "2020-08-02"
class_date: "2020-07-31"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
    highlight: tango
    number_sections: FALSE
menu:
  class:
    parent: Practicas
    weight: 1
type: docs
weight: 1
editor_options:
  chunk_output_type: console
---

<!-- BLOGDOWN-HEAD -->
<script src="/rmarkdown-libs/clipboard/clipboard.min.js"></script>
<link href="/rmarkdown-libs/primer-tooltips/build.css" rel="stylesheet" />
<link href="/rmarkdown-libs/klippy/css/klippy.min.css" rel="stylesheet" />
<script src="/rmarkdown-libs/klippy/js/klippy.min.js"></script>
<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  { background-color: #f8f8f8; }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>
<!-- /BLOGDOWN-HEAD -->

<h2>Índice</h2>
<div id="TOC">
<ul>
<li><a href="#objetivo">Objetivo</a></li>
<li><a href="#librerías">Librerías</a></li>
<li><a href="#datos">Datos</a><ul>
<li><a href="#explorar-datos">Explorar datos</a></li>
</ul></li>
<li><a href="#conceptos-centrales">Conceptos centrales</a><ul>
<li><a href="#probabilidades">Probabilidades</a></li>
<li><a href="#odds">Odds</a></li>
<li><a href="#odds-ratio-or">Odds Ratio (OR)</a></li>
<li><a href="#referencias">Referencias</a></li>
</ul></li>
<li><a href="#foro-práctica-9">Foro práctica 9</a></li>
</ul>
</div>

<script>
  addClassKlippyTo("pre.r, pre.markdown");
  addKlippy('right', 'bottom', 'auto', '1', 'Copy code', 'Copied!');
</script>
<div id="objetivo" class="section level1">
<h1>Objetivo</h1>
<p>La siguiente práctica tiene el objetivo de introducir a los estudiantes en los <strong>modelos de regresión logística</strong>, que es una técnica de análisis que nos permite tener una variable dependiente como <strong>dicotómica</strong>. Para ello, utilizaremos la base de datos del Titanic.</p>
</div>
<div id="librerías" class="section level1">
<h1>Librerías</h1>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1">pacman<span class="op">::</span><span class="kw">p_load</span>(dplyr, summarytools, ggmosaic, finalfit)</a></code></pre></div>
</div>
<div id="datos" class="section level1">
<h1>Datos</h1>
<p>¿Qué es el titanic? El <strong>RMS Titanic</strong> fue un transatlántico británico, el mayor barco del mundo al finalizar su construcción, que se hundió en la madrugada del 15 de abril de 1912 durante su viaje inaugural desde Southampton a Nueva York. En el hundimiento del Titanic <strong>murieron 619 personas</strong> de las <strong>1046</strong> que iban a bordo, lo que convierte a esta tragedia en uno de los mayores naufragios de la historia ocurridos en tiempo de paz.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" title="1"><span class="co">#Cargamos la base de datos desde internet</span></a>
<a class="sourceLine" id="cb2-2" title="2"><span class="kw">load</span>(<span class="kw">url</span>(<span class="st">&quot;https://multivariada.netlify.com/assignment/data/titanic.RData&quot;</span>))</a></code></pre></div>
<div id="explorar-datos" class="section level2">
<h2>Explorar datos</h2>
<p>A partir de la siguiente tabla se obtienen estadísticos descriptivos que luego serán relevantes para la interpretación de nuestros modelos.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1"><span class="kw">view</span>(<span class="kw">dfSummary</span>(tt, <span class="dt">headings =</span> <span class="ot">FALSE</span>, <span class="dt">method =</span> <span class="st">&quot;render&quot;</span>))</a></code></pre></div>
<div class="container st-container">
<table class="table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline ">
  <thead>
    <tr>
      <th align="center" class="st-protect-top-border"><strong>No</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Variable</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Stats / Values</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Freqs (% of Valid)</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Graph</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Valid</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Missing</strong></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td align="center">1</td>
      <td align="left">pclass
[factor]</td>
      <td align="left">1. Clase Alta
2. Clase Intermedia
3. Clase Baja</td>
      <td align="left" style="padding:0;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">284</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">27.2%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">261</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">24.9%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">501</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">47.9%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr></table></td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFQAAABQBAMAAAB11E/kAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqb39/f///+DdZCQAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5AgCDDMcMgiwZQAAAFVJREFUSMft1LsJACAMRVFXyAjGDXT/3Wxs/JKAhcK99WkMPEP4K10Upa/RVOagUOiGOrYlhl6hi1ft6HysDIVCL1DHDMXQK1QNHb7i8XpQKNS/rV+qAuxzd1RX56kAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjAtMDgtMDJUMTY6NTE6MjgtMDQ6MDAJE5qTAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIwLTA4LTAyVDE2OjUxOjI4LTA0OjAweE4iLwAAAABJRU5ErkJggg=="></td>
      <td align="center">1046
(100%)</td>
      <td align="center">0
(0%)</td>
    </tr>
    <tr>
      <td align="center">2</td>
      <td align="left">survived
[factor]</td>
      <td align="left">1. No sobrevive
2. Sobrevive</td>
      <td align="left" style="padding:0;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">619</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">59.2%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">427</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">40.8%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr></table></td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGUAAAA4BAMAAAAWQivVAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqb39/f///+DdZCQAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5AgCDDMcMgiwZQAAAD9JREFUSMdjYBh+QIkEoADVo2xMPBjVM6pnVM/w1kNOGSJIAhAYAnoIeBurHvxhbTSqZ1TPqJ4RpIecMmQ4AQD+619KnM2iBwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMC0wOC0wMlQxNjo1MToyOC0wNDowMAkTmpMAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjAtMDgtMDJUMTY6NTE6MjgtMDQ6MDB4TiIvAAAAAElFTkSuQmCC"></td>
      <td align="center">1046
(100%)</td>
      <td align="center">0
(0%)</td>
    </tr>
    <tr>
      <td align="center">3</td>
      <td align="left">sex
[factor]</td>
      <td align="left">1. Hombre
2. Mujer</td>
      <td align="left" style="padding:0;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">658</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">62.9%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">388</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">37.1%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr></table></td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGsAAAA4BAMAAAAIixtmAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqb39/f///+DdZCQAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5AgCDDMcMgiwZQAAAENJREFUSMdjYBjeQIk0oADVpmxMEhjVNqptVNuoNqzayCyCBEkDAkNJGz7/49GGJwKMRrWNahvVNqqNWG1kFkHDFQAA++po2kYgxFsAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjAtMDgtMDJUMTY6NTE6MjgtMDQ6MDAJE5qTAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIwLTA4LTAyVDE2OjUxOjI4LTA0OjAweE4iLwAAAABJRU5ErkJggg=="></td>
      <td align="center">1046
(100%)</td>
      <td align="center">0
(0%)</td>
    </tr>
    <tr>
      <td align="center">4</td>
      <td align="left">age
[numeric]</td>
      <td align="left">Mean (sd) : 29.9 (14.4)
min < med < max:
0.2 < 28 < 80
IQR (CV) : 18 (0.5)</td>
      <td align="left" style="vertical-align:middle">98 distinct values</td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqby8vL///8shn5hAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5AgCDDMcMgiwZQAAALZJREFUaN7t19sNgCAMhWFW0A3EDXT/3RSiiTekBTRe/vPWRD95gBaNISmptqntmKbSJYj1Y8DAwMB0mLYNnWKtcnVgYGBgD8NcT7SlMGd0YGB3Yn4Hl8J8AQb2b0x4pGSYcHVgYGAyTPAnK8f6+EQGuxqL3GJ0WGQgTNjqk7nY6ikwsK9h4fOZgIVX9w7MTimCbd+/CzseoomYK/Y9PAPb72AwsDdgc3NoSmBz4cXlxSU7hqRkAEk6BEewjvp3AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIwLTA4LTAyVDE2OjUxOjI4LTA0OjAwCROakwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMC0wOC0wMlQxNjo1MToyOC0wNDowMHhOIi8AAAAASUVORK5CYII="></td>
      <td align="center">1046
(100%)</td>
      <td align="center">0
(0%)</td>
    </tr>
    <tr>
      <td align="center">5</td>
      <td align="left">sibsp
[numeric]</td>
      <td align="left">Mean (sd) : 0.5 (0.9)
min < med < max:
0 < 0 < 8
IQR (CV) : 1 (1.8)</td>
      <td align="left" style="padding:0;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">0</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">685</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">65.5%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">1</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">280</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">26.8%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">2</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">36</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">3.4%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">3</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">16</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">1.5%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">4</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">22</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">2.1%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">5</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">6</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">0.6%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">8</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">1</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">0.1%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr></table></td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG8AAACwBAMAAADzgy2pAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqb39/f///+DdZCQAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5AgCDDMcMgiwZQAAAIxJREFUaN7t1rERgCAQRFFKkA7E60D6700DQwbdY8Yb9G/+AjbYI6V/ZFOzXtCqGCAQCBzYnKxmCYOtZ5QnsNUqEAgE3kD35mQ1E8KzCx+0ugOBQKAK3ZujqVDYvzAdaEAgEPgidI+VyGI/uk5o4pUDAoHAkc0R2ZRQ7QYIBAJDoOoCYQECgcAZ4NdzAC1L9TDuaHLRAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIwLTA4LTAyVDE2OjUxOjI4LTA0OjAwCROakwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMC0wOC0wMlQxNjo1MToyOC0wNDowMHhOIi8AAAAASUVORK5CYII="></td>
      <td align="center">1046
(100%)</td>
      <td align="center">0
(0%)</td>
    </tr>
    <tr>
      <td align="center">6</td>
      <td align="left">parch
[numeric]</td>
      <td align="left">Mean (sd) : 0.4 (0.8)
min < med < max:
0 < 0 < 6
IQR (CV) : 1 (2)</td>
      <td align="left" style="padding:0;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">0</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">768</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">73.4%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">1</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">160</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">15.3%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">2</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">97</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">9.3%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">3</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">8</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">0.8%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">4</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">5</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">0.5%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">5</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">6</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">0.6%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">6</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">2</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">0.2%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr></table></td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHoAAACwBAMAAAAyBGcFAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqb39/f///+DdZCQAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5AgCDDMcMgiwZQAAAIVJREFUaN7t1cENgCAQBEBbsAS1A+2/Nz88eJlwhOSQ2f882EuWbVs3ZyxFX08kN03T9EDdt2t7LAl0/Zh2XXV+0zRN59B9u9YgfqVLYUdMl4vRNE0n0n271qgS6Zavj6Zpmv7WMZxBz9s5TdP0CB3D8+t5L0bTND1Cx3AGfdA0TdOVXjEvSagtgJmu7p8AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjAtMDgtMDJUMTY6NTE6MjgtMDQ6MDAJE5qTAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIwLTA4LTAyVDE2OjUxOjI4LTA0OjAweE4iLwAAAABJRU5ErkJggg=="></td>
      <td align="center">1046
(100%)</td>
      <td align="center">0
(0%)</td>
    </tr>
  </tbody>
</table>
<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 0.9.6 (<a href='https://www.r-project.org/'>R</a> version 4.0.2)<br/>2020-08-02</p>
</div>
<p>Para esta práctica nos centraremos en las variables <code>sex</code> y <code>survived</code>. Como podemos notar la categoría de respuesta de estas variables son 0 y 1, es decir, estamos ante variables dicotómicas.</p>
<p>Con la función <code>ctable</code> del paquete <code>summarytools</code> podemos realizar una tabla de contingencia donde se señala la proporción de sobrevivientes según sexo</p>
<div class="container st-container">
<h3>Cross-Tabulation, Row Proportions</h3>
<h4>survived * sex</h4>
<strong>Data Frame</strong>: tt
<br/>
<table class="table table-bordered st-table st-table-bordered st-cross-table ">
<thead>
<tr>
<th></th>
<th colspan="8" align="center" class="st-protect-top-border">sex</th>
<th colspan="4"></th>
</tr>
<tr>
<td align="center">
<strong>survived</strong>
</td>
<th colspan="4" align="center">Hombre</th>
<th colspan="4" align="center">Mujer</th>
<th colspan="4" align="center">Total</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<strong align="center">No sobrevive</strong>
</td>
<td align="right" style="padding:0 0 0 15px;border-right:0;text-align:right">523</td>
<td align="left" style="padding:0 1px 0 4px;border-left:0;border-right:0;text-align:left">(</td>
<td align="left" style="padding:0;border-left:0;border-right:0;text-align:right">84.5%</td>
<td align="left" style="padding:0 15px 0 1px;border-left:0;text-align:right">)</td>
<td align="right" style="padding:0 0 0 15px;border-right:0;text-align:right">96</td>
<td align="left" style="padding:0 1px 0 4px;border-left:0;border-right:0;text-align:left">(</td>
<td align="left" style="padding:0;border-left:0;border-right:0;text-align:right">15.5%</td>
<td align="left" style="padding:0 15px 0 1px;border-left:0;text-align:right">)</td>
<td align="right" style="padding:0 0 0 15px;border-right:0;text-align:right">619</td>
<td align="left" style="padding:0 1px 0 4px;border-left:0;border-right:0;text-align:left">(</td>
<td align="left" style="padding:0;border-left:0;border-right:0;text-align:right">100.0%</td>
<td align="left" style="padding:0 15px 0 1px;border-left:0;text-align:right">)</td>
</tr>
<tr>
<td>
<strong align="center">Sobrevive</strong>
</td>
<td align="right" style="padding:0 0 0 15px;border-right:0;text-align:right">135</td>
<td align="left" style="padding:0 1px 0 4px;border-left:0;border-right:0;text-align:left">(</td>
<td align="left" style="padding:0;border-left:0;border-right:0;text-align:right">31.6%</td>
<td align="left" style="padding:0 15px 0 1px;border-left:0;text-align:right">)</td>
<td align="right" style="padding:0 0 0 15px;border-right:0;text-align:right">292</td>
<td align="left" style="padding:0 1px 0 4px;border-left:0;border-right:0;text-align:left">(</td>
<td align="left" style="padding:0;border-left:0;border-right:0;text-align:right">68.4%</td>
<td align="left" style="padding:0 15px 0 1px;border-left:0;text-align:right">)</td>
<td align="right" style="padding:0 0 0 15px;border-right:0;text-align:right">427</td>
<td align="left" style="padding:0 1px 0 4px;border-left:0;border-right:0;text-align:left">(</td>
<td align="left" style="padding:0;border-left:0;border-right:0;text-align:right">100.0%</td>
<td align="left" style="padding:0 15px 0 1px;border-left:0;text-align:right">)</td>
</tr>
<tr>
<td>
<strong align="center">Total</strong>
</td>
<td align="right" style="padding:0 0 0 15px;border-right:0;text-align:right">658</td>
<td align="left" style="padding:0 1px 0 4px;border-left:0;border-right:0;text-align:left">(</td>
<td align="left" style="padding:0;border-left:0;border-right:0;text-align:right">62.9%</td>
<td align="left" style="padding:0 15px 0 1px;border-left:0;text-align:right">)</td>
<td align="right" style="padding:0 0 0 15px;border-right:0;text-align:right">388</td>
<td align="left" style="padding:0 1px 0 4px;border-left:0;border-right:0;text-align:left">(</td>
<td align="left" style="padding:0;border-left:0;border-right:0;text-align:right">37.1%</td>
<td align="left" style="padding:0 15px 0 1px;border-left:0;text-align:right">)</td>
<td align="right" style="padding:0 0 0 15px;border-right:0;text-align:right">1046</td>
<td align="left" style="padding:0 1px 0 4px;border-left:0;border-right:0;text-align:left">(</td>
<td align="left" style="padding:0;border-left:0;border-right:0;text-align:right">100.0%</td>
<td align="left" style="padding:0 15px 0 1px;border-left:0;text-align:right">)</td>
</tr>
</tbody>
</table>
<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 0.9.6 (<a href='https://www.r-project.org/'>R</a> version 4.0.2)<br/>2020-08-02</p>
</div>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" title="1"><span class="kw">ctable</span>(tt<span class="op">$</span>survived, tt<span class="op">$</span>sex)</a></code></pre></div>
<p>La tabla muestra que la mayoría de los tripulantes no sobrevivió (619 no sobreviven, mientras que 427 si sobreviven). A su vez, la mayoría de los <em>no sobrevivientes</em> corresponden a hombres (84.5%), mientras que solo un 15.5% de las mujeres no sobrevive. En relación a sobrevivientes, la mayoría de los <em>sobrevivientes</em> corresponden a mujeres (68,4%), en desmedro de hombres (31.6%).</p>
<p>Una forma gráfica de verlo es por medio del paquete <code>ggmosaic</code> que con su función <code>geom_mosaic</code> permite construir visualizaciones para datos categóricos. El mosaico general corresponde al total de tripulantes del titanic. Como podrán notar, hay más hombres tripulantes que mujeres, por lo que las barras para hombres son mas anchas. Luego, gracias al comando <code>fill</code> del <code>geom_mosaic</code> podemos distinguir en hombres y mujeres la proporción de cuantos <strong>sobrevivieron</strong> y cuantos <strong>no sobrevivieron</strong>.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> tt) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb5-2" title="2"><span class="st">  </span><span class="kw">geom_mosaic</span>(<span class="kw">aes</span>(<span class="kw">product</span>(survived, sex), <span class="dt">fill=</span> survived)) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="st">&quot;Sobreviviente&quot;</span>, <span class="dt">x =</span> <span class="st">&quot;Sexo&quot;</span>)</a></code></pre></div>
<p><img src="/assignment/09-code_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
</div>
<div id="conceptos-centrales" class="section level1">
<h1>Conceptos centrales</h1>
<p>Los dos conceptos centrales en regresión logística son las “chances” (o en inglés, <strong>odds</strong>) y la razón (o en inglés, <strong>ratio</strong>).</p>
<div id="probabilidades" class="section level2">
<h2>Probabilidades</h2>
<p>Una <strong>probabilidad</strong> es la posibilidad de ocurrencia de un evento de interés, usando como referencia todos los eventos. Por ejemplo, la probabilidad de “ser sobreviviente en el titanic” se calcula en relación a todos los tripulantes del titanic.</p>
<p>En primera instancia, podríamos decir que del total de pasajeros, un 40.8% de ellos sobrevive, es decir, la probabilidad de sobrevivir es de 0.408</p>
<p><span class="math display">\[Probabilidades_{sobrevivientes} = \frac{427}{1046} = 0.408\]</span>
Mientras que un 59.2% de los tripulantes no sobrevive, es decir, la probabilidad de no sobrevivir es de 0.592</p>
<p><span class="math display">\[Probabilidades_{sobrevivientes} = \frac{619}{1046} = 0.592\]</span></p>
<p>En R se realiza a través de la función <code>prop.table</code></p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" title="1"><span class="kw">prop.table</span>(<span class="kw">table</span>(tt<span class="op">$</span>survived))</a></code></pre></div>
<pre><code>## 
## No sobrevive    Sobrevive 
##    0.5917782    0.4082218</code></pre>
</div>
<div id="odds" class="section level2">
<h2>Odds</h2>
<p>Una forma alternativa de representar una probabilidad es un <strong>odds</strong> que se definen como la división entre el número de ocurrencias (<span class="math inline">\(\pi\)</span>) y el numero de “no ocurrencias” (<span class="math inline">\(1-\pi\)</span>).</p>
<p><span class="math display">\[Odd =  \frac{\pi}{1-\pi}\]</span></p>
<p>Si seguimos el ejemplo del Titanic</p>
<p><span class="math display">\[Odds = \frac{Sobrevivientes}{No{Sobrevivientes}}\]</span></p>
<p>La función <code>addmargins</code> nos entrega las frecuencias marginales y absolutas para columnas (sexo) y filas (sobrevivencia)</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" title="1"><span class="kw">addmargins</span>(<span class="kw">table</span>(tt<span class="op">$</span>survived,tt<span class="op">$</span>sex))</a></code></pre></div>
<pre><code>##               
##                Hombre Mujer  Sum
##   No sobrevive    523    96  619
##   Sobrevive       135   292  427
##   Sum             658   388 1046</code></pre>
<p>Si hacemos el cálculo de los <strong>odds</strong> obtenemos 0.68 (427/619), es decir, hay 0.68 sobrevivientes por cada no sobreviviente. Aunque parezca poco “lógico” hablar de 0.68 sobrevivientes, esto indica que la relación entre sobrevivientes y no sobrevivientes no es 1:1 y de hecho <strong>existen más chances de morir que de sobrevivir</strong>.</p>
<p>Otra forma de leer este dato es decir que por cada 100 no sobrevivientes, hay 68 sobrevivientes.</p>
<p>Podríamos también calcular el <strong>odds</strong> de sobrevivencia de hombres y mujeres</p>
<p><span class="math display">\[Odds{hombres} = \frac{135}{523} = 0.258\]</span>
<span class="math display">\[Odds{mujeres} = \frac{292}{96} = 3.04\]</span></p>
<p>Para los hombres, hay más chances de no sobrevivir que de sobrevivir (odds &lt; 1), mientras que para mujeres hay más chances de sobrevivir que de no sobrevivir (odds &gt; 1)</p>
<p><strong>Propiedades de Odds</strong></p>
<ul>
<li>Odds <strong>menores</strong> que 1, indican una chance negativa</li>
<li>Odds <strong>mayores</strong> que 1, indican una chance positiva</li>
</ul>
<p>En R esto podemos realizar este calculo directamente a través de las probabilidades marginales para cada sexo que entrega <code>prop.table</code>.El número 2 indica que las proporciones están calculadas por columna, es decir, las probabilidades indicadas se calculan considerando como total cada sexo.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" title="1"><span class="kw">prop.table</span>(<span class="kw">table</span>(tt<span class="op">$</span>survived,tt<span class="op">$</span>sex),<span class="dv">2</span>)</a></code></pre></div>
<pre><code>##               
##                   Hombre     Mujer
##   No sobrevive 0.7948328 0.2474227
##   Sobrevive    0.2051672 0.7525773</code></pre>
</div>
<div id="odds-ratio-or" class="section level2">
<h2>Odds Ratio (OR)</h2>
<p>Ahora bien, con los datos hasta ahí podriamos llegar a la conclusión de que las mujeres tienen más chances de sobrevivir que los hombres. Pero, <strong>¿cuánto más sobreviven las mujeres que los hombres?</strong></p>
<p>Esta pregunta implica la <strong>asociación</strong> entre <code>sobrevivencia</code> y <code>sexo</code> y ya no solo hablar de las chances de sobrevivencia de cada sexo por separado. Para hacer esa relación se requiere calcular los <code>odds ratio</code> o razón de chances.</p>
<p><span class="math display">\[Odds Ratio = \frac{Odds_{mujeres}}{Odds_{hombres}} = \frac{3.04}{0.258} = 11.78\]</span></p>
<p>El resultado que obtenemos se lee de la siguiente manera: las chances de sobrevivir de las mujeres es 11.78 veces más grande que la de los hombres.</p>
<p>En consecuencia, la comparación de los Odds de dos grupos es conocido como <strong>Odds Ratio (OR)</strong>. Formalmente:</p>
<p><span class="math display">\[Odds_{ratio}=\frac{odds_{1}}{odds_{2}}=\frac{\pi_{1}/(1-\pi_{1})}{\pi_{2}/(1-\pi_{2})}\]</span></p>
<p><strong>Propiedades de Odds Ratio:</strong></p>
<ul>
<li><p>Cuando X e Y son independientes <span class="math inline">\(Odds_{ratio}\)</span> ya que <span class="math inline">\(odds_{1}=odds_{2}\)</span></p></li>
<li><p>El rango de posibles valores es: <span class="math inline">\(0&lt;Odds_{ratio}&lt;\infty\)</span></p>
<ul>
<li><p>Cuando los valores van de 0 a 1, <span class="math inline">\(Odds_{ratio}\)</span> indica que <span class="math inline">\(odds_{1}&lt;odds_{2}\)</span></p></li>
<li><p>Cuando los valores van de 1 a <span class="math inline">\(\infty\)</span>, <span class="math inline">\(Odds_{ratio}\)</span> indica que <span class="math inline">\(odds_{1}&gt;odds_{2}\)</span></p></li>
</ul></li>
<li><p>Es una medida de magnitud de asociación simétrica: un <span class="math inline">\(Odds_{ratio}=4\)</span> es una asociación positiva proporcional a la asociación negativa <span class="math inline">\(Odds_{ratio}=1/4=0.25\)</span></p></li>
</ul>
<p>Los <span class="math inline">\(Odds_{ratio}\)</span> se pueden graficar por medio de la funcion <code>or_plor</code> de <code>finalfit</code>. Para ello solo de debe indicar cuál es la variable predictora (o explanatory en inglés) y la variable dependiente.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" title="1">explanatory =<span class="st"> &quot;sex&quot;</span></a>
<a class="sourceLine" id="cb12-2" title="2">dependent =<span class="st"> &quot;survived&quot;</span></a>
<a class="sourceLine" id="cb12-3" title="3"></a>
<a class="sourceLine" id="cb12-4" title="4">tt <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">or_plot</span>(dependent, explanatory)</a></code></pre></div>
<p><img src="/assignment/09-code_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Como se puede ver, en el gráfico no solo se indican los <span class="math inline">\(Odds_{ratio}\)</span> de sobrevivencia de las mujeres por sobre los hombres (11.78), sino que estos se grafican en relacióna qué tan cerca están del 0 (y por tanto, cuánto se aleja del rango de asociación negativa).</p>
</div>
<div id="referencias" class="section level2">
<h2>Referencias</h2>
<p><a href="https://multivariada.netlify.app/docs/lecturas/Camarero_Odd_Ratio_LogitV2.pdf">Camarero et al (2017) Regresión logística: Fundamentos y aplicación a la investigación sociológica (p.1-29)</a></p>
<p><a href="https://scielo.conicyt.cl/scielo.php?script=sci_arttext&amp;pid=S0034-98872013001000014">Cerda, Vera y Rada (2017) Odds ratio: aspectos teóricos y prácticos.</a></p>
</div>
</div>
<div id="foro-práctica-9" class="section level1">
<h1>Foro práctica 9</h1>
</div>
